env:
  browser: true
  es2021: true
  node: true
extends:
  - standard
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  comma-dangle: 'off'
  react/prop-types: 'off' # not a fan
