// flow-typed signature: 32831ec87b644754f8d85a88eb37aeef
// flow-typed version: <<STUB>>/@nodeproto/buildproto_vworkspace:0.0.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nodeproto/buildproto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nodeproto/buildproto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nodeproto/buildproto/dist/esbuild/create.esbuild.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/esbuild/index.esbuild.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/esbuild/plugins/_pluginTemplate' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/esbuild/plugins/fixtures/sourcedir/copytooutdir' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/esbuild/plugins/index.esbuild.plugin' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/esbuild/plugins/popCopy.esbuild.plugin' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/esbuild/run.esbuild.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/base.webpack.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/bff/server.webpack' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/build.webpack.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/index.webpack.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/prod.webpack.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/react.dev.webpack.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/react.esbuild.webpack.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/setup.webpack.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/test.compiler' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/fixtures/auto' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/fixtures/react' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nodeproto/buildproto/dist/esbuild/create.esbuild.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild/create.esbuild.config'>;
}
declare module '@nodeproto/buildproto/dist/esbuild/index.esbuild.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild/index.esbuild.config'>;
}
declare module '@nodeproto/buildproto/dist/esbuild/plugins/_pluginTemplate.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild/plugins/_pluginTemplate'>;
}
declare module '@nodeproto/buildproto/dist/esbuild/plugins/fixtures/sourcedir/copytooutdir.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild/plugins/fixtures/sourcedir/copytooutdir'>;
}
declare module '@nodeproto/buildproto/dist/esbuild/plugins/index.esbuild.plugin.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild/plugins/index.esbuild.plugin'>;
}
declare module '@nodeproto/buildproto/dist/esbuild/plugins/popCopy.esbuild.plugin.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild/plugins/popCopy.esbuild.plugin'>;
}
declare module '@nodeproto/buildproto/dist/esbuild/run.esbuild.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild/run.esbuild.config'>;
}
declare module '@nodeproto/buildproto/dist/index' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist'>;
}
declare module '@nodeproto/buildproto/dist/index.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist'>;
}
declare module '@nodeproto/buildproto/dist/webpack/base.webpack.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/base.webpack.config'>;
}
declare module '@nodeproto/buildproto/dist/webpack/bff/server.webpack.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/bff/server.webpack'>;
}
declare module '@nodeproto/buildproto/dist/webpack/build.webpack.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/build.webpack.config'>;
}
declare module '@nodeproto/buildproto/dist/webpack/index.webpack.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/index.webpack.config'>;
}
declare module '@nodeproto/buildproto/dist/webpack/prod.webpack.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/prod.webpack.config'>;
}
declare module '@nodeproto/buildproto/dist/webpack/react.dev.webpack.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/react.dev.webpack.config'>;
}
declare module '@nodeproto/buildproto/dist/webpack/react.esbuild.webpack.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/react.esbuild.webpack.config'>;
}
declare module '@nodeproto/buildproto/dist/webpack/setup.webpack.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/setup.webpack.config'>;
}
declare module '@nodeproto/buildproto/dist/webpack/test.compiler.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/test.compiler'>;
}
declare module '@nodeproto/buildproto/fixtures/auto.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/fixtures/auto'>;
}
declare module '@nodeproto/buildproto/fixtures/react.jsx' {
  declare module.exports: $Exports<'@nodeproto/buildproto/fixtures/react'>;
}
