// flow-typed signature: 52e098ed332f8994faa18c91a2ec0a7c
// flow-typed version: <<STUB>>/@nodeproto/buildproto_vworkspace:0.0.0/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nodeproto/buildproto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nodeproto/buildproto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nodeproto/buildproto/dist/esbuild/base.esbuild.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/esbuild' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/esbuild/plugins' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/esbuild/plugins/popCopy' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/esbuild/plugins/popCopy/popCopy.esbuild.plugin' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/esbuild/run.esbuild.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/esm_import_yml-YMVRFTBV' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/fixtures/auto' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/fixtures/commonjs' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/fixtures/esm_import_yml' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/fixtures/esm' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/libdefs/buildproto' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/libdefs/esbuild' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/libdefs/external' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/libdefs' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/libdefs/webpack' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/pack' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/base.webpack.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/bff' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/bff/server.webpack' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/build.webpack.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/esbuild.webpack.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/prod.webpack.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/react.webpack.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/test.compiler' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/dist/webpack/utility.webpack.config' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@babel/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@babel/eslint-parser_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@babel/eslint-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@babel/plugin-syntax-top-level-await_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@babel/plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@babel/runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@babel/traverse_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@changesets/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@nodeproto/configproto_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@nodeproto/eslint-config_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@nodeproto/jsync_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@nodeproto/prettier-config_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@nodeproto/shared_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@nodeproto/testproto_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@nodeproto/wtf_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@octokit/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/@octokit/rest_v18.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/babel-preset-nodeproto_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/browserslist_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/bundle-stats-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/chokidar-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/colors_v1.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/copy-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/core-js_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/css-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/csv-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/esbuild_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/esbuild-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/esbuild-plugin-manifest_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/eslint-config-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-fb-flow_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-html_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-json_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-markdown_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-node_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-promise_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-yml_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/flow-remove-types_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/fs-extra_v8.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/glob_v7.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/globby_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/hoist-non-react-statics_v3.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/html-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/http-terminator_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/jest_v27.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/json5_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/koa_v2.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/md5_v2.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/memfs_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/mini-svg-data-uri_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/mkdirp_v1.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/node-stream-zip_v1.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/prettier_v1.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/react-devtools_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/react-dom_v18.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/react-dom_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/regenerator-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/rimraf_v3.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/schema-utils_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/semver_v7.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/string-replace-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/style-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/terser-webpack-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/ultra-runner_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/uvu_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/webpack_v5.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/webpack-dev-middleware-2_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/webpack-hot-middleware-2_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/webpack-manifest-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/yaml-eslint-parser_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/yamljs_v0.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/flow-typed/npm/yargs_v15.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/src/fixtures/auto' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/src/libdefs/buildproto' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/src/libdefs/esbuild' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/src/libdefs/external' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/src/libdefs' {
  declare module.exports: any;
}

declare module '@nodeproto/buildproto/src/libdefs/webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nodeproto/buildproto/dist/esbuild/base.esbuild.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild/base.esbuild.config'>;
}
declare module '@nodeproto/buildproto/dist/esbuild/index' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild'>;
}
declare module '@nodeproto/buildproto/dist/esbuild/index.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild'>;
}
declare module '@nodeproto/buildproto/dist/esbuild/plugins/index' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild/plugins'>;
}
declare module '@nodeproto/buildproto/dist/esbuild/plugins/index.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild/plugins'>;
}
declare module '@nodeproto/buildproto/dist/esbuild/plugins/popCopy/index' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild/plugins/popCopy'>;
}
declare module '@nodeproto/buildproto/dist/esbuild/plugins/popCopy/index.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild/plugins/popCopy'>;
}
declare module '@nodeproto/buildproto/dist/esbuild/plugins/popCopy/popCopy.esbuild.plugin.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild/plugins/popCopy/popCopy.esbuild.plugin'>;
}
declare module '@nodeproto/buildproto/dist/esbuild/run.esbuild.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esbuild/run.esbuild.config'>;
}
declare module '@nodeproto/buildproto/dist/esm_import_yml-YMVRFTBV.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/esm_import_yml-YMVRFTBV'>;
}
declare module '@nodeproto/buildproto/dist/fixtures/auto.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/fixtures/auto'>;
}
declare module '@nodeproto/buildproto/dist/fixtures/commonjs.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/fixtures/commonjs'>;
}
declare module '@nodeproto/buildproto/dist/fixtures/esm_import_yml.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/fixtures/esm_import_yml'>;
}
declare module '@nodeproto/buildproto/dist/fixtures/esm.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/fixtures/esm'>;
}
declare module '@nodeproto/buildproto/dist/index' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist'>;
}
declare module '@nodeproto/buildproto/dist/index.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist'>;
}
declare module '@nodeproto/buildproto/dist/libdefs/buildproto.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/libdefs/buildproto'>;
}
declare module '@nodeproto/buildproto/dist/libdefs/esbuild.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/libdefs/esbuild'>;
}
declare module '@nodeproto/buildproto/dist/libdefs/external.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/libdefs/external'>;
}
declare module '@nodeproto/buildproto/dist/libdefs/index' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/libdefs'>;
}
declare module '@nodeproto/buildproto/dist/libdefs/index.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/libdefs'>;
}
declare module '@nodeproto/buildproto/dist/libdefs/webpack.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/libdefs/webpack'>;
}
declare module '@nodeproto/buildproto/dist/pack.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/pack'>;
}
declare module '@nodeproto/buildproto/dist/webpack/base.webpack.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/base.webpack.config'>;
}
declare module '@nodeproto/buildproto/dist/webpack/bff/index' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/bff'>;
}
declare module '@nodeproto/buildproto/dist/webpack/bff/index.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/bff'>;
}
declare module '@nodeproto/buildproto/dist/webpack/bff/server.webpack.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/bff/server.webpack'>;
}
declare module '@nodeproto/buildproto/dist/webpack/build.webpack.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/build.webpack.config'>;
}
declare module '@nodeproto/buildproto/dist/webpack/esbuild.webpack.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/esbuild.webpack.config'>;
}
declare module '@nodeproto/buildproto/dist/webpack/index' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack'>;
}
declare module '@nodeproto/buildproto/dist/webpack/index.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack'>;
}
declare module '@nodeproto/buildproto/dist/webpack/prod.webpack.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/prod.webpack.config'>;
}
declare module '@nodeproto/buildproto/dist/webpack/react.webpack.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/react.webpack.config'>;
}
declare module '@nodeproto/buildproto/dist/webpack/test.compiler.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/test.compiler'>;
}
declare module '@nodeproto/buildproto/dist/webpack/utility.webpack.config.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/dist/webpack/utility.webpack.config'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@babel/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@babel/cli_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@babel/eslint-parser_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@babel/eslint-parser_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@babel/eslint-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@babel/eslint-plugin_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@babel/plugin-syntax-top-level-await_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@babel/plugin-syntax-top-level-await_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@babel/plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@babel/plugin-transform-flow-strip-types_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@babel/runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@babel/runtime_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@babel/traverse_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@babel/traverse_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@changesets/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@changesets/cli_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@nodeproto/configproto_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@nodeproto/configproto_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@nodeproto/eslint-config_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@nodeproto/eslint-config_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@nodeproto/jsync_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@nodeproto/jsync_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@nodeproto/prettier-config_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@nodeproto/prettier-config_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@nodeproto/shared_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@nodeproto/shared_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@nodeproto/testproto_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@nodeproto/testproto_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@nodeproto/wtf_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@nodeproto/wtf_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@octokit/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@octokit/core_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/@octokit/rest_v18.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/@octokit/rest_v18.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/babel-preset-nodeproto_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/babel-preset-nodeproto_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/browserslist_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/browserslist_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/bundle-stats-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/bundle-stats-webpack-plugin_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/chokidar-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/chokidar-cli_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/colors_v1.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/colors_v1.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/copy-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/copy-webpack-plugin_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/core-js_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/core-js_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/css-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/css-loader_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/csv-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/csv-loader_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/esbuild_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/esbuild_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/esbuild-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/esbuild-loader_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/esbuild-plugin-manifest_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/esbuild-plugin-manifest_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/eslint-config-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/eslint-config-prettier_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-fb-flow_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/eslint-plugin-fb-flow_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-html_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/eslint-plugin-html_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-json_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/eslint-plugin-json_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-markdown_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/eslint-plugin-markdown_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-node_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/eslint-plugin-node_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/eslint-plugin-prettier_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-promise_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/eslint-plugin-promise_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/eslint-plugin-yml_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/eslint-plugin-yml_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/flow-remove-types_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/flow-remove-types_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/fs-extra_v8.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/fs-extra_v8.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/glob_v7.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/glob_v7.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/globby_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/globby_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/hoist-non-react-statics_v3.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/hoist-non-react-statics_v3.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/html-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/html-webpack-plugin_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/http-terminator_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/http-terminator_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/husky_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/jest_v27.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/jest_v27.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/json5_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/json5_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/koa_v2.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/koa_v2.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/md5_v2.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/md5_v2.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/memfs_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/memfs_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/mini-svg-data-uri_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/mini-svg-data-uri_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/mkdirp_v1.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/mkdirp_v1.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/node-stream-zip_v1.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/node-stream-zip_v1.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/prettier_v1.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/prettier_v1.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/prettier_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/react-devtools_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/react-devtools_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/react-dom_v18.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/react-dom_v18.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/react-dom_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/react-dom_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/regenerator-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/regenerator-runtime_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/rimraf_v3.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/rimraf_v3.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/schema-utils_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/schema-utils_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/semver_v7.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/semver_v7.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/string-replace-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/string-replace-loader_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/style-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/style-loader_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/terser-webpack-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/terser-webpack-plugin_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/ultra-runner_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/ultra-runner_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/uvu_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/uvu_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/webpack_v5.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/webpack_v5.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/webpack-dev-middleware-2_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/webpack-dev-middleware-2_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/webpack-hot-middleware-2_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/webpack-hot-middleware-2_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/webpack-manifest-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/webpack-manifest-plugin_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/yaml-eslint-parser_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/yaml-eslint-parser_vx.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/yamljs_v0.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/yamljs_v0.x.x'>;
}
declare module '@nodeproto/buildproto/flow-typed/npm/yargs_v15.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/flow-typed/npm/yargs_v15.x.x'>;
}
declare module '@nodeproto/buildproto/src/fixtures/auto.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/src/fixtures/auto'>;
}
declare module '@nodeproto/buildproto/src/libdefs/buildproto.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/src/libdefs/buildproto'>;
}
declare module '@nodeproto/buildproto/src/libdefs/esbuild.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/src/libdefs/esbuild'>;
}
declare module '@nodeproto/buildproto/src/libdefs/external.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/src/libdefs/external'>;
}
declare module '@nodeproto/buildproto/src/libdefs/index' {
  declare module.exports: $Exports<'@nodeproto/buildproto/src/libdefs'>;
}
declare module '@nodeproto/buildproto/src/libdefs/index.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/src/libdefs'>;
}
declare module '@nodeproto/buildproto/src/libdefs/webpack.js' {
  declare module.exports: $Exports<'@nodeproto/buildproto/src/libdefs/webpack'>;
}
