// flow-typed signature: b105c2c534d42eeb76e74d7ea01825e1
// flow-typed version: <<STUB>>/contains-path_v1.0.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'contains-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'contains-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'contains-path/index' {
  declare module.exports: $Exports<'contains-path'>;
}
declare module 'contains-path/index.js' {
  declare module.exports: $Exports<'contains-path'>;
}
