// flow-typed signature: cdc86aa6e652fdc12e23840069c34c76
// flow-typed version: <<STUB>>/dirent_v2.0.1/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dirent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dirent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dirent/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dirent/index' {
  declare module.exports: $Exports<'dirent'>;
}
declare module 'dirent/index.js' {
  declare module.exports: $Exports<'dirent'>;
}
declare module 'dirent/utils.js' {
  declare module.exports: $Exports<'dirent/utils'>;
}
