// flow-typed signature: 0c9d9d92c0e9d1cc20082865dbe41886
// flow-typed version: <<STUB>>/jsonc-simple-parser_v2.2.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonc-simple-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonc-simple-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonc-simple-parser/dist/detokenize' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist/lookup' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist/parse' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist/stringify' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist/strip' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist/strip/parser' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist/strip/tokens' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist/tokenize/context' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist/tokenize/grammar' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist/tokenize' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist/tokenize/parser' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist/tokenize/tokens' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist/types' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist/utils' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/dist/validate' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/tasks/benchmark' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/test/lib/fixtures' {
  declare module.exports: any;
}

declare module 'jsonc-simple-parser/test/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonc-simple-parser/dist/detokenize.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/detokenize'>;
}
declare module 'jsonc-simple-parser/dist/index' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist'>;
}
declare module 'jsonc-simple-parser/dist/index.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist'>;
}
declare module 'jsonc-simple-parser/dist/lookup.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/lookup'>;
}
declare module 'jsonc-simple-parser/dist/parse.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/parse'>;
}
declare module 'jsonc-simple-parser/dist/stringify.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/stringify'>;
}
declare module 'jsonc-simple-parser/dist/strip/index' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/strip'>;
}
declare module 'jsonc-simple-parser/dist/strip/index.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/strip'>;
}
declare module 'jsonc-simple-parser/dist/strip/parser.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/strip/parser'>;
}
declare module 'jsonc-simple-parser/dist/strip/tokens.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/strip/tokens'>;
}
declare module 'jsonc-simple-parser/dist/tokenize/context.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/tokenize/context'>;
}
declare module 'jsonc-simple-parser/dist/tokenize/grammar.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/tokenize/grammar'>;
}
declare module 'jsonc-simple-parser/dist/tokenize/index' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/tokenize'>;
}
declare module 'jsonc-simple-parser/dist/tokenize/index.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/tokenize'>;
}
declare module 'jsonc-simple-parser/dist/tokenize/parser.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/tokenize/parser'>;
}
declare module 'jsonc-simple-parser/dist/tokenize/tokens.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/tokenize/tokens'>;
}
declare module 'jsonc-simple-parser/dist/types.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/types'>;
}
declare module 'jsonc-simple-parser/dist/utils.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/utils'>;
}
declare module 'jsonc-simple-parser/dist/validate.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/dist/validate'>;
}
declare module 'jsonc-simple-parser/tasks/benchmark.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/tasks/benchmark'>;
}
declare module 'jsonc-simple-parser/test/lib/fixtures.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/test/lib/fixtures'>;
}
declare module 'jsonc-simple-parser/test/lib/index' {
  declare module.exports: $Exports<'jsonc-simple-parser/test/lib'>;
}
declare module 'jsonc-simple-parser/test/lib/index.js' {
  declare module.exports: $Exports<'jsonc-simple-parser/test/lib'>;
}
