// flow-typed signature: 93d459d72edd88ee869107b591ef43af
// flow-typed version: <<STUB>>/symlink-dir_v5.0.1/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'symlink-dir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'symlink-dir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'symlink-dir/dist/cli' {
  declare module.exports: any;
}

declare module 'symlink-dir/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'symlink-dir/dist/cli.js' {
  declare module.exports: $Exports<'symlink-dir/dist/cli'>;
}
declare module 'symlink-dir/dist/index' {
  declare module.exports: $Exports<'symlink-dir/dist'>;
}
declare module 'symlink-dir/dist/index.js' {
  declare module.exports: $Exports<'symlink-dir/dist'>;
}
