// flow-typed signature: f93a6aeeb081a877ee4ebc3df6dc3fee
// flow-typed version: <<STUB>>/@formatjs/icu-messageformat-parser_v2.0.18/flow_v0.170.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@formatjs/icu-messageformat-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@formatjs/icu-messageformat-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@formatjs/icu-messageformat-parser/error' {
  declare module.exports: any;
}

declare module '@formatjs/icu-messageformat-parser/lib/error' {
  declare module.exports: any;
}

declare module '@formatjs/icu-messageformat-parser/lib' {
  declare module.exports: any;
}

declare module '@formatjs/icu-messageformat-parser/lib/manipulator' {
  declare module.exports: any;
}

declare module '@formatjs/icu-messageformat-parser/lib/no-parser' {
  declare module.exports: any;
}

declare module '@formatjs/icu-messageformat-parser/lib/parser' {
  declare module.exports: any;
}

declare module '@formatjs/icu-messageformat-parser/lib/printer' {
  declare module.exports: any;
}

declare module '@formatjs/icu-messageformat-parser/lib/regex.generated' {
  declare module.exports: any;
}

declare module '@formatjs/icu-messageformat-parser/lib/types' {
  declare module.exports: any;
}

declare module '@formatjs/icu-messageformat-parser/manipulator' {
  declare module.exports: any;
}

declare module '@formatjs/icu-messageformat-parser/no-parser' {
  declare module.exports: any;
}

declare module '@formatjs/icu-messageformat-parser/parser' {
  declare module.exports: any;
}

declare module '@formatjs/icu-messageformat-parser/printer' {
  declare module.exports: any;
}

declare module '@formatjs/icu-messageformat-parser/regex.generated' {
  declare module.exports: any;
}

declare module '@formatjs/icu-messageformat-parser/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@formatjs/icu-messageformat-parser/error.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/error'>;
}
declare module '@formatjs/icu-messageformat-parser/index' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser'>;
}
declare module '@formatjs/icu-messageformat-parser/index.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser'>;
}
declare module '@formatjs/icu-messageformat-parser/lib/error.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/lib/error'>;
}
declare module '@formatjs/icu-messageformat-parser/lib/index' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/lib'>;
}
declare module '@formatjs/icu-messageformat-parser/lib/index.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/lib'>;
}
declare module '@formatjs/icu-messageformat-parser/lib/manipulator.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/lib/manipulator'>;
}
declare module '@formatjs/icu-messageformat-parser/lib/no-parser.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/lib/no-parser'>;
}
declare module '@formatjs/icu-messageformat-parser/lib/parser.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/lib/parser'>;
}
declare module '@formatjs/icu-messageformat-parser/lib/printer.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/lib/printer'>;
}
declare module '@formatjs/icu-messageformat-parser/lib/regex.generated.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/lib/regex.generated'>;
}
declare module '@formatjs/icu-messageformat-parser/lib/types.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/lib/types'>;
}
declare module '@formatjs/icu-messageformat-parser/manipulator.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/manipulator'>;
}
declare module '@formatjs/icu-messageformat-parser/no-parser.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/no-parser'>;
}
declare module '@formatjs/icu-messageformat-parser/parser.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/parser'>;
}
declare module '@formatjs/icu-messageformat-parser/printer.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/printer'>;
}
declare module '@formatjs/icu-messageformat-parser/regex.generated.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/regex.generated'>;
}
declare module '@formatjs/icu-messageformat-parser/types.js' {
  declare module.exports: $Exports<'@formatjs/icu-messageformat-parser/types'>;
}
