// flow-typed signature: 01a3c4a770e3f73b782778882a4595a6
// flow-typed version: <<STUB>>/browserslist_v4.16.8/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browserslist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browserslist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browserslist/browser' {
  declare module.exports: any;
}

declare module 'browserslist/cli' {
  declare module.exports: any;
}

declare module 'browserslist/error' {
  declare module.exports: any;
}

declare module 'browserslist/node' {
  declare module.exports: any;
}

declare module 'browserslist/update-db' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browserslist/browser.js' {
  declare module.exports: $Exports<'browserslist/browser'>;
}
declare module 'browserslist/cli.js' {
  declare module.exports: $Exports<'browserslist/cli'>;
}
declare module 'browserslist/error.js' {
  declare module.exports: $Exports<'browserslist/error'>;
}
declare module 'browserslist/index' {
  declare module.exports: $Exports<'browserslist'>;
}
declare module 'browserslist/index.js' {
  declare module.exports: $Exports<'browserslist'>;
}
declare module 'browserslist/node.js' {
  declare module.exports: $Exports<'browserslist/node'>;
}
declare module 'browserslist/update-db.js' {
  declare module.exports: $Exports<'browserslist/update-db'>;
}
