// flow-typed signature: f6266f56d7574ef244b7f43ba80afc97
// flow-typed version: <<STUB>>/chai-exclude_v2.0.3/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-exclude'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-exclude' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai-exclude/chai-exclude' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai-exclude/chai-exclude.js' {
  declare module.exports: $Exports<'chai-exclude/chai-exclude'>;
}
