// flow-typed signature: 40ad41b5a8a0385dfa4e74153311c9da
// flow-typed version: <<STUB>>/chai-nock_v1.3.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-nock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-nock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai-nock/test/requested.test' {
  declare module.exports: any;
}

declare module 'chai-nock/test/requestedWithExactBody.test' {
  declare module.exports: any;
}

declare module 'chai-nock/test/requestedWithHeaders.test' {
  declare module.exports: any;
}

declare module 'chai-nock/test/requestedWithHeadersMatch.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai-nock/index' {
  declare module.exports: $Exports<'chai-nock'>;
}
declare module 'chai-nock/index.js' {
  declare module.exports: $Exports<'chai-nock'>;
}
declare module 'chai-nock/test/requested.test.js' {
  declare module.exports: $Exports<'chai-nock/test/requested.test'>;
}
declare module 'chai-nock/test/requestedWithExactBody.test.js' {
  declare module.exports: $Exports<'chai-nock/test/requestedWithExactBody.test'>;
}
declare module 'chai-nock/test/requestedWithHeaders.test.js' {
  declare module.exports: $Exports<'chai-nock/test/requestedWithHeaders.test'>;
}
declare module 'chai-nock/test/requestedWithHeadersMatch.test.js' {
  declare module.exports: $Exports<'chai-nock/test/requestedWithHeadersMatch.test'>;
}
