// flow-typed signature: 965a81f3bf9f9b4d1f2f833054f0f55e
// flow-typed version: <<STUB>>/kleur_v4.1.4/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kleur'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kleur' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kleur/colors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kleur/colors.js' {
  declare module.exports: $Exports<'kleur/colors'>;
}
declare module 'kleur/index' {
  declare module.exports: $Exports<'kleur'>;
}
declare module 'kleur/index.js' {
  declare module.exports: $Exports<'kleur'>;
}
