// flow-typed signature: b7728e8afa4aafad00ee349bd4377ed8
// flow-typed version: <<STUB>>/uvu_v0.5.1/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uvu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uvu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uvu/assert' {
  declare module.exports: any;
}

declare module 'uvu/bin' {
  declare module.exports: any;
}

declare module 'uvu/diff' {
  declare module.exports: any;
}

declare module 'uvu/dist' {
  declare module.exports: any;
}

declare module 'uvu/parse' {
  declare module.exports: any;
}

declare module 'uvu/run' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uvu/assert/index' {
  declare module.exports: $Exports<'uvu/assert'>;
}
declare module 'uvu/assert/index.js' {
  declare module.exports: $Exports<'uvu/assert'>;
}
declare module 'uvu/bin.js' {
  declare module.exports: $Exports<'uvu/bin'>;
}
declare module 'uvu/diff/index' {
  declare module.exports: $Exports<'uvu/diff'>;
}
declare module 'uvu/diff/index.js' {
  declare module.exports: $Exports<'uvu/diff'>;
}
declare module 'uvu/dist/index' {
  declare module.exports: $Exports<'uvu/dist'>;
}
declare module 'uvu/dist/index.js' {
  declare module.exports: $Exports<'uvu/dist'>;
}
declare module 'uvu/parse/index' {
  declare module.exports: $Exports<'uvu/parse'>;
}
declare module 'uvu/parse/index.js' {
  declare module.exports: $Exports<'uvu/parse'>;
}
declare module 'uvu/run/index' {
  declare module.exports: $Exports<'uvu/run'>;
}
declare module 'uvu/run/index.js' {
  declare module.exports: $Exports<'uvu/run'>;
}
