// flow-typed signature: 97322f15317cb9198c75716197cd3699
// flow-typed version: <<STUB>>/@nodeproto/envproto_vworkspace:0.0.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nodeproto/envproto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nodeproto/envproto' {
  declare module.exports: any;
}
