// flow-typed signature: 6d07b84a7368d0c3aa86e359c224f0b6
// flow-typed version: <<STUB>>/@babel/eslint-plugin_v7.17.7/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-plugin' {
  declare module.exports: any;
}
