#!/usr/bin/env bash

# expected output if ./proto -f=proto cmd=blah blah blah
# ./bin/proto "$*"

cmd="./bin/$1"
shift
args="$*"

if test -f "$cmd"; then
  $cmd $args
else
  echo file does not exist
fi
