# -*- mode: ruby -*-
# vi: set ft=ruby :

# TODO: move to 12-factor
# @nodeproto
# @see https://docs.vagrantup.com
ENV["LC_ALL"] = "en_US.UTF-8"
Vagrant.require_version ">= 2.2"

# vagrant config version 2
Vagrant.configure("2") do |config|
  # @see https://app.vagrantup.com/generic
  config.vm.box = "generic/alpine314"
  config.vm.box_check_update = true # check for updates
  config.vm.box_version = "3.4.2" # set to > 0 to get the latest

  # TODO: move to packages/tools/membrane
  config.vm.provision :shell, path: "src/vagrant/bootstrap.sh"

  config.vm.network "private_network", type: "dhcp" # create a private network for nfs
  # map to apps
  config.vm.network "forwarded_port",
    guest: 8080, host: 8080, protocol: "tcp"
  config.vm.network "forwarded_port",
    guest: 8097, host: 8097, protocol: "udp"
  config.vm.network "forwarded_port",
    guest: 7777, host: 7777, protocol: "tcp"
  config.vm.network "forwarded_port",
    guest: 3000, host: 3000, protocol: "tcp"
  config.vm.network "forwarded_port",
    guest: 3443, host: 3443, protocol: "tcp"

  # nfs > virtualbox synced folder
  config.vm.synced_folder ".", "/opt/nodeproto",
    type: "nfs",
    nfs_export: true,
    nfs_udp: false,
    verify_installed: true,
    linux__nfs_options: ['rw','no_subtree_check','all_squash','async'] # make the NFS share asynchronous

  # virtual box config
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false # TODO: enable this for react-dev-tools if we cant forward it from host
    vb.memory = "1024" # Customize the amount of memory on the VM:
    vb.cpus = 2 # max cores
    vb.linked_clone = true # the master is generated by importing the base box only once the first time it is required.
    vb.check_guest_additions = true # takes a perf hit but increase stability
    # TODO: set this to like 20 to imitate prod-type resources
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "70"] # host CPU execution cap of 70%,
  end
end

# config.vm.network "public_network" # Create a public network, which generally matched to bridged network.
