// flow-typed signature: 6a1fc6321bc7c27ab87c109d74479966
// flow-typed version: <<STUB>>/@nodeproto/jsync_vworkspace:*/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nodeproto/jsync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nodeproto/jsync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nodeproto/jsync/bin/jsync' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nodeproto/jsync/bin/jsync.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/bin/jsync'>;
}
