// flow-typed signature: 4c23d97e53917b7e250524449ab5c757
// flow-typed version: <<STUB>>/@nodeproto/shared_vworkspace:0.0.0/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nodeproto/shared'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nodeproto/shared' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nodeproto/shared/dist' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/dist/libdefs' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/dist/opsproto/errors' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/dist/opsproto' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/dist/opsproto/logging' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/dist/opsproto/sortFunctions' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/dist/opsproto/utility' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/dist/wtf/dirnamefilename' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/dist/wtf/fixtures/cjs' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/dist/wtf/fixtures/mjs' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/dist/wtf' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/dist/wtf/readdir' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/@babel/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/@babel/eslint-parser_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/@babel/eslint-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/@babel/runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/@folder/readdir_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/@nodeproto/configproto_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/@nodeproto/eslint-config_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/@nodeproto/prettier-config_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/@nodeproto/testproto_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/@octokit/rest_v18.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/@swc/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/@swc/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/babel-preset-nodeproto_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/browserslist_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/chokidar-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/colors_v1.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/eslint-config-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-fb-flow_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-html_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-json_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-markdown_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-node_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-promise_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-yml_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/fs-extra_v8.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/glob_v7.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/jest_v27.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/jsonc-simple-parser_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/md5_v2.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/mkdirp_v1.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/node-stream-zip_v1.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/picomatch_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/prettier_v1.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/regenerator-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/rimraf_v3.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/semver_v7.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/ultra-runner_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/flow-typed/npm/uvu_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/shared/src/libdefs' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nodeproto/shared/dist/index' {
  declare module.exports: $Exports<'@nodeproto/shared/dist'>;
}
declare module '@nodeproto/shared/dist/index.js' {
  declare module.exports: $Exports<'@nodeproto/shared/dist'>;
}
declare module '@nodeproto/shared/dist/libdefs/index' {
  declare module.exports: $Exports<'@nodeproto/shared/dist/libdefs'>;
}
declare module '@nodeproto/shared/dist/libdefs/index.js' {
  declare module.exports: $Exports<'@nodeproto/shared/dist/libdefs'>;
}
declare module '@nodeproto/shared/dist/opsproto/errors.js' {
  declare module.exports: $Exports<'@nodeproto/shared/dist/opsproto/errors'>;
}
declare module '@nodeproto/shared/dist/opsproto/index' {
  declare module.exports: $Exports<'@nodeproto/shared/dist/opsproto'>;
}
declare module '@nodeproto/shared/dist/opsproto/index.js' {
  declare module.exports: $Exports<'@nodeproto/shared/dist/opsproto'>;
}
declare module '@nodeproto/shared/dist/opsproto/logging.js' {
  declare module.exports: $Exports<'@nodeproto/shared/dist/opsproto/logging'>;
}
declare module '@nodeproto/shared/dist/opsproto/sortFunctions.js' {
  declare module.exports: $Exports<'@nodeproto/shared/dist/opsproto/sortFunctions'>;
}
declare module '@nodeproto/shared/dist/opsproto/utility.js' {
  declare module.exports: $Exports<'@nodeproto/shared/dist/opsproto/utility'>;
}
declare module '@nodeproto/shared/dist/wtf/dirnamefilename.js' {
  declare module.exports: $Exports<'@nodeproto/shared/dist/wtf/dirnamefilename'>;
}
declare module '@nodeproto/shared/dist/wtf/fixtures/cjs.js' {
  declare module.exports: $Exports<'@nodeproto/shared/dist/wtf/fixtures/cjs'>;
}
declare module '@nodeproto/shared/dist/wtf/fixtures/mjs.js' {
  declare module.exports: $Exports<'@nodeproto/shared/dist/wtf/fixtures/mjs'>;
}
declare module '@nodeproto/shared/dist/wtf/index' {
  declare module.exports: $Exports<'@nodeproto/shared/dist/wtf'>;
}
declare module '@nodeproto/shared/dist/wtf/index.js' {
  declare module.exports: $Exports<'@nodeproto/shared/dist/wtf'>;
}
declare module '@nodeproto/shared/dist/wtf/readdir.js' {
  declare module.exports: $Exports<'@nodeproto/shared/dist/wtf/readdir'>;
}
declare module '@nodeproto/shared/flow-typed/npm/@babel/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/@babel/cli_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/@babel/eslint-parser_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/@babel/eslint-parser_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/@babel/eslint-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/@babel/eslint-plugin_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/@babel/runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/@babel/runtime_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/@folder/readdir_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/@folder/readdir_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/@nodeproto/configproto_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/@nodeproto/configproto_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/@nodeproto/eslint-config_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/@nodeproto/eslint-config_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/@nodeproto/prettier-config_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/@nodeproto/prettier-config_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/@nodeproto/testproto_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/@nodeproto/testproto_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/@octokit/rest_v18.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/@octokit/rest_v18.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/@swc/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/@swc/cli_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/@swc/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/@swc/core_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/babel-preset-nodeproto_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/babel-preset-nodeproto_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/browserslist_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/browserslist_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/chokidar-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/chokidar-cli_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/colors_v1.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/colors_v1.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/eslint-config-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/eslint-config-prettier_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-fb-flow_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/eslint-plugin-fb-flow_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-html_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/eslint-plugin-html_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-json_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/eslint-plugin-json_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-markdown_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/eslint-plugin-markdown_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-node_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/eslint-plugin-node_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/eslint-plugin-prettier_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-promise_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/eslint-plugin-promise_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/eslint-plugin-yml_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/eslint-plugin-yml_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/fs-extra_v8.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/fs-extra_v8.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/glob_v7.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/glob_v7.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/husky_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/jest_v27.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/jest_v27.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/jsonc-simple-parser_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/jsonc-simple-parser_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/md5_v2.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/md5_v2.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/mkdirp_v1.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/mkdirp_v1.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/node-stream-zip_v1.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/node-stream-zip_v1.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/picomatch_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/picomatch_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/prettier_v1.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/prettier_v1.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/prettier_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/regenerator-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/regenerator-runtime_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/rimraf_v3.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/rimraf_v3.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/semver_v7.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/semver_v7.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/ultra-runner_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/ultra-runner_vx.x.x'>;
}
declare module '@nodeproto/shared/flow-typed/npm/uvu_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/shared/flow-typed/npm/uvu_vx.x.x'>;
}
declare module '@nodeproto/shared/src/libdefs/index' {
  declare module.exports: $Exports<'@nodeproto/shared/src/libdefs'>;
}
declare module '@nodeproto/shared/src/libdefs/index.js' {
  declare module.exports: $Exports<'@nodeproto/shared/src/libdefs'>;
}
