// flow-typed signature: d6d102e0acd3f9b9d4b59b61777f4c74
// flow-typed version: <<STUB>>/@nodeproto/wtf_vworkspace:*/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nodeproto/wtf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nodeproto/wtf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nodeproto/wtf/dist/dirs' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/dist/esmain' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/dist/fsproto' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nodeproto/wtf/dist/dirs.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/dist/dirs'>;
}
declare module '@nodeproto/wtf/dist/esmain.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/dist/esmain'>;
}
declare module '@nodeproto/wtf/dist/fsproto.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/dist/fsproto'>;
}
declare module '@nodeproto/wtf/dist/index' {
  declare module.exports: $Exports<'@nodeproto/wtf/dist'>;
}
declare module '@nodeproto/wtf/dist/index.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/dist'>;
}
