'use strict';

import CircularDependencyPlugin from 'circular-dependency-plugin';
import HtmlWebpackPlugin from 'html-webpack-plugin';
import path from 'path';
import pkgJson from '../package.json';
import ScriptExtHtmlWebpackPlugin from 'script-ext-html-webpack-plugin';
import webpack from 'webpack';
import webpackBaseConfig from './webpack.base.config.mjs';
import babelConfig from './babel.config.mjs';

export default webpackBaseConfig({
  babelConfig: babelConfig(),
  pkgJson,
  // entryUnshift: ['webpack-hot-middleware/client?reload=false'],
  plugins: [
    new webpack.HotModuleReplacementPlugin(),

    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: pkgJson.config.HTML_INDEX,
    }),

    new ScriptExtHtmlWebpackPlugin({
      module: /(workers|sw)/,
    }),
  ],
  devServer: {
    contentBase: path.resolve(process.cwd(), pkgJson.directories.dist),
    hot: true,
  },
});
