// flow-typed signature: c62c7de434e871df7d7fca128e6ad676
// flow-typed version: <<STUB>>/@babel/eslint-plugin_v7.16.5/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/eslint-plugin/lib' {
  declare module.exports: any;
}

declare module '@babel/eslint-plugin/lib/rules/new-cap' {
  declare module.exports: any;
}

declare module '@babel/eslint-plugin/lib/rules/no-invalid-this' {
  declare module.exports: any;
}

declare module '@babel/eslint-plugin/lib/rules/no-unused-expressions' {
  declare module.exports: any;
}

declare module '@babel/eslint-plugin/lib/rules/object-curly-spacing' {
  declare module.exports: any;
}

declare module '@babel/eslint-plugin/lib/rules/semi' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/eslint-plugin/lib/index' {
  declare module.exports: $Exports<'@babel/eslint-plugin/lib'>;
}
declare module '@babel/eslint-plugin/lib/index.js' {
  declare module.exports: $Exports<'@babel/eslint-plugin/lib'>;
}
declare module '@babel/eslint-plugin/lib/rules/new-cap.js' {
  declare module.exports: $Exports<'@babel/eslint-plugin/lib/rules/new-cap'>;
}
declare module '@babel/eslint-plugin/lib/rules/no-invalid-this.js' {
  declare module.exports: $Exports<'@babel/eslint-plugin/lib/rules/no-invalid-this'>;
}
declare module '@babel/eslint-plugin/lib/rules/no-unused-expressions.js' {
  declare module.exports: $Exports<'@babel/eslint-plugin/lib/rules/no-unused-expressions'>;
}
declare module '@babel/eslint-plugin/lib/rules/object-curly-spacing.js' {
  declare module.exports: $Exports<'@babel/eslint-plugin/lib/rules/object-curly-spacing'>;
}
declare module '@babel/eslint-plugin/lib/rules/semi.js' {
  declare module.exports: $Exports<'@babel/eslint-plugin/lib/rules/semi'>;
}
