// flow-typed signature: bd963d481eb73f6f6c18525933f48dd8
// flow-typed version: <<STUB>>/string-replace-loader_v3.0.2/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-replace-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-replace-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'string-replace-loader/lib/getOptionsArray' {
  declare module.exports: any;
}

declare module 'string-replace-loader/lib/processChunk' {
  declare module.exports: any;
}

declare module 'string-replace-loader/lib/replace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'string-replace-loader/index' {
  declare module.exports: $Exports<'string-replace-loader'>;
}
declare module 'string-replace-loader/index.js' {
  declare module.exports: $Exports<'string-replace-loader'>;
}
declare module 'string-replace-loader/lib/getOptionsArray.js' {
  declare module.exports: $Exports<'string-replace-loader/lib/getOptionsArray'>;
}
declare module 'string-replace-loader/lib/processChunk.js' {
  declare module.exports: $Exports<'string-replace-loader/lib/processChunk'>;
}
declare module 'string-replace-loader/lib/replace.js' {
  declare module.exports: $Exports<'string-replace-loader/lib/replace'>;
}
