// flow-typed signature: 35ccefdc72ba790e6e29f5e82abe1369
// flow-typed version: <<STUB>>/@changesets/cli_v2.20.0/flow_v0.170.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@changesets/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@changesets/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@changesets/cli/bin' {
  declare module.exports: any;
}

declare module '@changesets/cli/changelog/dist/cli.cjs.dev' {
  declare module.exports: any;
}

declare module '@changesets/cli/changelog/dist/cli.cjs' {
  declare module.exports: any;
}

declare module '@changesets/cli/changelog/dist/cli.cjs.prod' {
  declare module.exports: any;
}

declare module '@changesets/cli/changelog/dist/cli.esm' {
  declare module.exports: any;
}

declare module '@changesets/cli/dist/cli.cjs.dev' {
  declare module.exports: any;
}

declare module '@changesets/cli/dist/cli.cjs' {
  declare module.exports: any;
}

declare module '@changesets/cli/dist/cli.cjs.prod' {
  declare module.exports: any;
}

declare module '@changesets/cli/dist/cli.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@changesets/cli/bin.js' {
  declare module.exports: $Exports<'@changesets/cli/bin'>;
}
declare module '@changesets/cli/changelog/dist/cli.cjs.dev.js' {
  declare module.exports: $Exports<'@changesets/cli/changelog/dist/cli.cjs.dev'>;
}
declare module '@changesets/cli/changelog/dist/cli.cjs.js' {
  declare module.exports: $Exports<'@changesets/cli/changelog/dist/cli.cjs'>;
}
declare module '@changesets/cli/changelog/dist/cli.cjs.prod.js' {
  declare module.exports: $Exports<'@changesets/cli/changelog/dist/cli.cjs.prod'>;
}
declare module '@changesets/cli/changelog/dist/cli.esm.js' {
  declare module.exports: $Exports<'@changesets/cli/changelog/dist/cli.esm'>;
}
declare module '@changesets/cli/dist/cli.cjs.dev.js' {
  declare module.exports: $Exports<'@changesets/cli/dist/cli.cjs.dev'>;
}
declare module '@changesets/cli/dist/cli.cjs.js' {
  declare module.exports: $Exports<'@changesets/cli/dist/cli.cjs'>;
}
declare module '@changesets/cli/dist/cli.cjs.prod.js' {
  declare module.exports: $Exports<'@changesets/cli/dist/cli.cjs.prod'>;
}
declare module '@changesets/cli/dist/cli.esm.js' {
  declare module.exports: $Exports<'@changesets/cli/dist/cli.esm'>;
}
