// flow-typed signature: f9544c8c9ca47549dab502d992d9bf54
// flow-typed version: <<STUB>>/chokidar-cli_v3.0.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chokidar-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chokidar-cli' {
  declare module.exports: any;
}
