// flow-typed signature: 584901bd7e4362d3a49381efdfe06d96
// flow-typed version: <<STUB>>/@nodeproto/utils_vworkspace:*/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nodeproto/utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nodeproto/utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nodeproto/utils/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nodeproto/utils/dist/index' {
  declare module.exports: $Exports<'@nodeproto/utils/dist'>;
}
declare module '@nodeproto/utils/dist/index.js' {
  declare module.exports: $Exports<'@nodeproto/utils/dist'>;
}
