"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault").default;

exports.__esModule = true;
exports.default = void 0;

var pack = _interopRequireDefault(require("./webpack.setup.mjs"));

var _webpackBaseConfig = _interopRequireDefault(require("./webpack.base.config.mjs"));

var _htmlWebpackPlugin = _interopRequireDefault(require("html-webpack-plugin"));

// @see https://webpack.js.org/guides/production/
var _default = (0, _webpackBaseConfig.default)({
  publicPath: './',
  plugins: [new _htmlWebpackPlugin.default({
    inject: true,
    // Inject all files that are generated by webpack, e.g. bundle.js
    template: pack.env.config.HTML_INDEX
  })]
});

exports.default = _default;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uL3dlYnBhY2svcHJvZC53ZWJwYWNrLmNvbmZpZy5tanMiXSwibmFtZXMiOlsicHVibGljUGF0aCIsInBsdWdpbnMiLCJIdG1sV2VicGFja1BsdWdpbiIsImluamVjdCIsInRlbXBsYXRlIiwicGFjayIsImVudiIsImNvbmZpZyIsIkhUTUxfSU5ERVgiXSwibWFwcGluZ3MiOiI7Ozs7Ozs7QUFBQTs7QUFDQTs7QUFDQTs7QUFFQTtlQUNlLGdDQUFrQjtBQUMvQkEsRUFBQUEsVUFBVSxFQUFFLElBRG1CO0FBRS9CQyxFQUFBQSxPQUFPLEVBQUUsQ0FDUCxJQUFJQywwQkFBSixDQUFzQjtBQUNwQkMsSUFBQUEsTUFBTSxFQUFFLElBRFk7QUFDTjtBQUNkQyxJQUFBQSxRQUFRLEVBQUVDLElBQUksQ0FBQ0MsR0FBTCxDQUFTQyxNQUFULENBQWdCQztBQUZOLEdBQXRCLENBRE87QUFGc0IsQ0FBbEIsQyIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCAqIGFzIHBhY2sgZnJvbSAnLi93ZWJwYWNrLnNldHVwLm1qcyc7XG5pbXBvcnQgd2VicGFja0Jhc2VDb25maWcgZnJvbSAnLi93ZWJwYWNrLmJhc2UuY29uZmlnLm1qcyc7XG5pbXBvcnQgSHRtbFdlYnBhY2tQbHVnaW4gZnJvbSAnaHRtbC13ZWJwYWNrLXBsdWdpbic7XG5cbi8vIEBzZWUgaHR0cHM6Ly93ZWJwYWNrLmpzLm9yZy9ndWlkZXMvcHJvZHVjdGlvbi9cbmV4cG9ydCBkZWZhdWx0IHdlYnBhY2tCYXNlQ29uZmlnKHtcbiAgcHVibGljUGF0aDogJy4vJyxcbiAgcGx1Z2luczogW1xuICAgIG5ldyBIdG1sV2VicGFja1BsdWdpbih7XG4gICAgICBpbmplY3Q6IHRydWUsIC8vIEluamVjdCBhbGwgZmlsZXMgdGhhdCBhcmUgZ2VuZXJhdGVkIGJ5IHdlYnBhY2ssIGUuZy4gYnVuZGxlLmpzXG4gICAgICB0ZW1wbGF0ZTogcGFjay5lbnYuY29uZmlnLkhUTUxfSU5ERVgsXG4gICAgfSksXG4gIF1cbn0pXG4iXX0=