// flow-typed signature: 7485bd81503c9f65da223d65289e3f12
// flow-typed version: <<STUB>>/@opentelemetry/tracing_v0.21.0/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@opentelemetry/tracing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@opentelemetry/tracing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@opentelemetry/tracing/build/esm/BasicTracerProvider' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/config' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/enums' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/export/BatchSpanProcessor' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/export/ConsoleSpanExporter' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/export/InMemorySpanExporter' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/export/NoopSpanProcessor' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/export/ReadableSpan' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/export/SimpleSpanProcessor' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/export/SpanExporter' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/MultiSpanProcessor' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/Span' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/SpanProcessor' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/TimedEvent' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/Tracer' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/types' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/utility' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/esm/version' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/BasicTracerProvider' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/config' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/enums' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/export/BatchSpanProcessor' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/export/ConsoleSpanExporter' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/export/InMemorySpanExporter' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/export/NoopSpanProcessor' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/export/ReadableSpan' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/export/SimpleSpanProcessor' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/export/SpanExporter' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/MultiSpanProcessor' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/Span' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/SpanProcessor' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/TimedEvent' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/Tracer' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/types' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/utility' {
  declare module.exports: any;
}

declare module '@opentelemetry/tracing/build/src/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@opentelemetry/tracing/build/esm/BasicTracerProvider.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/BasicTracerProvider'>;
}
declare module '@opentelemetry/tracing/build/esm/config.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/config'>;
}
declare module '@opentelemetry/tracing/build/esm/enums.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/enums'>;
}
declare module '@opentelemetry/tracing/build/esm/export/BatchSpanProcessor.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/export/BatchSpanProcessor'>;
}
declare module '@opentelemetry/tracing/build/esm/export/ConsoleSpanExporter.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/export/ConsoleSpanExporter'>;
}
declare module '@opentelemetry/tracing/build/esm/export/InMemorySpanExporter.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/export/InMemorySpanExporter'>;
}
declare module '@opentelemetry/tracing/build/esm/export/NoopSpanProcessor.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/export/NoopSpanProcessor'>;
}
declare module '@opentelemetry/tracing/build/esm/export/ReadableSpan.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/export/ReadableSpan'>;
}
declare module '@opentelemetry/tracing/build/esm/export/SimpleSpanProcessor.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/export/SimpleSpanProcessor'>;
}
declare module '@opentelemetry/tracing/build/esm/export/SpanExporter.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/export/SpanExporter'>;
}
declare module '@opentelemetry/tracing/build/esm/index' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm'>;
}
declare module '@opentelemetry/tracing/build/esm/index.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm'>;
}
declare module '@opentelemetry/tracing/build/esm/MultiSpanProcessor.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/MultiSpanProcessor'>;
}
declare module '@opentelemetry/tracing/build/esm/Span.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/Span'>;
}
declare module '@opentelemetry/tracing/build/esm/SpanProcessor.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/SpanProcessor'>;
}
declare module '@opentelemetry/tracing/build/esm/TimedEvent.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/TimedEvent'>;
}
declare module '@opentelemetry/tracing/build/esm/Tracer.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/Tracer'>;
}
declare module '@opentelemetry/tracing/build/esm/types.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/types'>;
}
declare module '@opentelemetry/tracing/build/esm/utility.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/utility'>;
}
declare module '@opentelemetry/tracing/build/esm/version.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/esm/version'>;
}
declare module '@opentelemetry/tracing/build/src/BasicTracerProvider.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/BasicTracerProvider'>;
}
declare module '@opentelemetry/tracing/build/src/config.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/config'>;
}
declare module '@opentelemetry/tracing/build/src/enums.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/enums'>;
}
declare module '@opentelemetry/tracing/build/src/export/BatchSpanProcessor.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/export/BatchSpanProcessor'>;
}
declare module '@opentelemetry/tracing/build/src/export/ConsoleSpanExporter.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/export/ConsoleSpanExporter'>;
}
declare module '@opentelemetry/tracing/build/src/export/InMemorySpanExporter.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/export/InMemorySpanExporter'>;
}
declare module '@opentelemetry/tracing/build/src/export/NoopSpanProcessor.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/export/NoopSpanProcessor'>;
}
declare module '@opentelemetry/tracing/build/src/export/ReadableSpan.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/export/ReadableSpan'>;
}
declare module '@opentelemetry/tracing/build/src/export/SimpleSpanProcessor.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/export/SimpleSpanProcessor'>;
}
declare module '@opentelemetry/tracing/build/src/export/SpanExporter.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/export/SpanExporter'>;
}
declare module '@opentelemetry/tracing/build/src/index' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src'>;
}
declare module '@opentelemetry/tracing/build/src/index.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src'>;
}
declare module '@opentelemetry/tracing/build/src/MultiSpanProcessor.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/MultiSpanProcessor'>;
}
declare module '@opentelemetry/tracing/build/src/Span.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/Span'>;
}
declare module '@opentelemetry/tracing/build/src/SpanProcessor.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/SpanProcessor'>;
}
declare module '@opentelemetry/tracing/build/src/TimedEvent.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/TimedEvent'>;
}
declare module '@opentelemetry/tracing/build/src/Tracer.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/Tracer'>;
}
declare module '@opentelemetry/tracing/build/src/types.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/types'>;
}
declare module '@opentelemetry/tracing/build/src/utility.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/utility'>;
}
declare module '@opentelemetry/tracing/build/src/version.js' {
  declare module.exports: $Exports<'@opentelemetry/tracing/build/src/version'>;
}
