// flow-typed signature: 4b53ecae32e07d410d761210a866c5ec
// flow-typed version: <<STUB>>/babel-plugin-transform-export-default-name_v2.1.0/flow_v0.173.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-export-default-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-export-default-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-export-default-name/dist/deriveName' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-export-default-name/dist' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-export-default-name/dist/normalizeName' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-export-default-name/dist/resolveConflictingName' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-export-default-name/dist/deriveName.js' {
  declare module.exports: $Exports<'babel-plugin-transform-export-default-name/dist/deriveName'>;
}
declare module 'babel-plugin-transform-export-default-name/dist/index' {
  declare module.exports: $Exports<'babel-plugin-transform-export-default-name/dist'>;
}
declare module 'babel-plugin-transform-export-default-name/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-export-default-name/dist'>;
}
declare module 'babel-plugin-transform-export-default-name/dist/normalizeName.js' {
  declare module.exports: $Exports<'babel-plugin-transform-export-default-name/dist/normalizeName'>;
}
declare module 'babel-plugin-transform-export-default-name/dist/resolveConflictingName.js' {
  declare module.exports: $Exports<'babel-plugin-transform-export-default-name/dist/resolveConflictingName'>;
}
