// flow-typed signature: 5d595c577253b9218d0c5e76f6643cf3
// flow-typed version: <<STUB>>/babel-plugin-tailcall-optimization_v2.0.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-tailcall-optimization'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-tailcall-optimization' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-tailcall-optimization/build/findTailCalls' {
  declare module.exports: any;
}

declare module 'babel-plugin-tailcall-optimization/build/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-tailcall-optimization/build/findTailCalls.js' {
  declare module.exports: $Exports<'babel-plugin-tailcall-optimization/build/findTailCalls'>;
}
declare module 'babel-plugin-tailcall-optimization/build/lib.js' {
  declare module.exports: $Exports<'babel-plugin-tailcall-optimization/build/lib'>;
}
