// flow-typed signature: f4e7c16541b9fb1f898705ae9ccd0af0
// flow-typed version: <<STUB>>/eslint-plugin-json_v3.1.0/flow_v0.164.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-json/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-json/src/index' {
  declare module.exports: $Exports<'eslint-plugin-json/src'>;
}
declare module 'eslint-plugin-json/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-json/src'>;
}
