// flow-typed signature: 6b2a0abf4a8aeedfc064e411eba13791
// flow-typed version: <<STUB>>/@babel/eslint-parser_v7.17.0/flow_v0.173.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
