// flow-typed signature: d984266f8ca7bfbbb10273690b68d1f9
// flow-typed version: <<STUB>>/@opentelemetry/api_v^1.0.0-rc.0/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@opentelemetry/api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@opentelemetry/api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@opentelemetry/api/build/esm/api/context' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/api/diag' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/api/propagation' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/api/trace' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/baggage/context-helpers' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/baggage/internal/baggage-impl' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/baggage/internal/symbol' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/baggage/types' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/baggage/utils' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/common/Exception' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/common/Time' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/context/context' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/context/NoopContextManager' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/context/types' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/diag/ComponentLogger' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/diag/consoleLogger' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/diag' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/diag/internal/logLevelLogger' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/diag/internal/noopLogger' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/diag/types' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/internal/global-utils' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/internal/semver' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/platform/browser/globalThis' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/platform/browser' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/platform' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/platform/node/globalThis' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/platform/node' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/propagation/NoopTextMapPropagator' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/propagation/TextMapPropagator' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/attributes' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/context-utils' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/link' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/NonRecordingSpan' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/NoopTracer' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/NoopTracerProvider' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/ProxyTracer' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/ProxyTracerProvider' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/Sampler' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/SamplingResult' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/span_context' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/span_kind' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/span' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/spancontext-utils' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/SpanOptions' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/status' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/trace_flags' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/trace_state' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/tracer_provider' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/trace/tracer' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/esm/version' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/api/context' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/api/diag' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/api/propagation' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/api/trace' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/baggage/context-helpers' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/baggage/internal/baggage-impl' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/baggage/internal/symbol' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/baggage/types' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/baggage/utils' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/common/Exception' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/common/Time' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/context/context' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/context/NoopContextManager' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/context/types' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/diag/ComponentLogger' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/diag/consoleLogger' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/diag' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/diag/internal/logLevelLogger' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/diag/internal/noopLogger' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/diag/types' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/internal/global-utils' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/internal/semver' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/platform/browser/globalThis' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/platform/browser' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/platform' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/platform/node/globalThis' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/platform/node' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/propagation/NoopTextMapPropagator' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/propagation/TextMapPropagator' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/attributes' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/context-utils' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/link' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/NonRecordingSpan' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/NoopTracer' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/NoopTracerProvider' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/ProxyTracer' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/ProxyTracerProvider' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/Sampler' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/SamplingResult' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/span_context' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/span_kind' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/span' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/spancontext-utils' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/SpanOptions' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/status' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/trace_flags' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/trace_state' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/tracer_provider' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/trace/tracer' {
  declare module.exports: any;
}

declare module '@opentelemetry/api/build/src/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@opentelemetry/api/build/esm/api/context.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/api/context'>;
}
declare module '@opentelemetry/api/build/esm/api/diag.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/api/diag'>;
}
declare module '@opentelemetry/api/build/esm/api/propagation.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/api/propagation'>;
}
declare module '@opentelemetry/api/build/esm/api/trace.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/api/trace'>;
}
declare module '@opentelemetry/api/build/esm/baggage/context-helpers.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/baggage/context-helpers'>;
}
declare module '@opentelemetry/api/build/esm/baggage/internal/baggage-impl.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/baggage/internal/baggage-impl'>;
}
declare module '@opentelemetry/api/build/esm/baggage/internal/symbol.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/baggage/internal/symbol'>;
}
declare module '@opentelemetry/api/build/esm/baggage/types.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/baggage/types'>;
}
declare module '@opentelemetry/api/build/esm/baggage/utils.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/baggage/utils'>;
}
declare module '@opentelemetry/api/build/esm/common/Exception.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/common/Exception'>;
}
declare module '@opentelemetry/api/build/esm/common/Time.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/common/Time'>;
}
declare module '@opentelemetry/api/build/esm/context/context.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/context/context'>;
}
declare module '@opentelemetry/api/build/esm/context/NoopContextManager.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/context/NoopContextManager'>;
}
declare module '@opentelemetry/api/build/esm/context/types.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/context/types'>;
}
declare module '@opentelemetry/api/build/esm/diag/ComponentLogger.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/diag/ComponentLogger'>;
}
declare module '@opentelemetry/api/build/esm/diag/consoleLogger.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/diag/consoleLogger'>;
}
declare module '@opentelemetry/api/build/esm/diag/index' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/diag'>;
}
declare module '@opentelemetry/api/build/esm/diag/index.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/diag'>;
}
declare module '@opentelemetry/api/build/esm/diag/internal/logLevelLogger.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/diag/internal/logLevelLogger'>;
}
declare module '@opentelemetry/api/build/esm/diag/internal/noopLogger.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/diag/internal/noopLogger'>;
}
declare module '@opentelemetry/api/build/esm/diag/types.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/diag/types'>;
}
declare module '@opentelemetry/api/build/esm/index' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm'>;
}
declare module '@opentelemetry/api/build/esm/index.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm'>;
}
declare module '@opentelemetry/api/build/esm/internal/global-utils.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/internal/global-utils'>;
}
declare module '@opentelemetry/api/build/esm/internal/semver.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/internal/semver'>;
}
declare module '@opentelemetry/api/build/esm/platform/browser/globalThis.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/platform/browser/globalThis'>;
}
declare module '@opentelemetry/api/build/esm/platform/browser/index' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/platform/browser'>;
}
declare module '@opentelemetry/api/build/esm/platform/browser/index.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/platform/browser'>;
}
declare module '@opentelemetry/api/build/esm/platform/index' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/platform'>;
}
declare module '@opentelemetry/api/build/esm/platform/index.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/platform'>;
}
declare module '@opentelemetry/api/build/esm/platform/node/globalThis.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/platform/node/globalThis'>;
}
declare module '@opentelemetry/api/build/esm/platform/node/index' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/platform/node'>;
}
declare module '@opentelemetry/api/build/esm/platform/node/index.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/platform/node'>;
}
declare module '@opentelemetry/api/build/esm/propagation/NoopTextMapPropagator.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/propagation/NoopTextMapPropagator'>;
}
declare module '@opentelemetry/api/build/esm/propagation/TextMapPropagator.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/propagation/TextMapPropagator'>;
}
declare module '@opentelemetry/api/build/esm/trace/attributes.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/attributes'>;
}
declare module '@opentelemetry/api/build/esm/trace/context-utils.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/context-utils'>;
}
declare module '@opentelemetry/api/build/esm/trace/link.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/link'>;
}
declare module '@opentelemetry/api/build/esm/trace/NonRecordingSpan.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/NonRecordingSpan'>;
}
declare module '@opentelemetry/api/build/esm/trace/NoopTracer.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/NoopTracer'>;
}
declare module '@opentelemetry/api/build/esm/trace/NoopTracerProvider.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/NoopTracerProvider'>;
}
declare module '@opentelemetry/api/build/esm/trace/ProxyTracer.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/ProxyTracer'>;
}
declare module '@opentelemetry/api/build/esm/trace/ProxyTracerProvider.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/ProxyTracerProvider'>;
}
declare module '@opentelemetry/api/build/esm/trace/Sampler.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/Sampler'>;
}
declare module '@opentelemetry/api/build/esm/trace/SamplingResult.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/SamplingResult'>;
}
declare module '@opentelemetry/api/build/esm/trace/span_context.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/span_context'>;
}
declare module '@opentelemetry/api/build/esm/trace/span_kind.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/span_kind'>;
}
declare module '@opentelemetry/api/build/esm/trace/span.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/span'>;
}
declare module '@opentelemetry/api/build/esm/trace/spancontext-utils.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/spancontext-utils'>;
}
declare module '@opentelemetry/api/build/esm/trace/SpanOptions.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/SpanOptions'>;
}
declare module '@opentelemetry/api/build/esm/trace/status.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/status'>;
}
declare module '@opentelemetry/api/build/esm/trace/trace_flags.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/trace_flags'>;
}
declare module '@opentelemetry/api/build/esm/trace/trace_state.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/trace_state'>;
}
declare module '@opentelemetry/api/build/esm/trace/tracer_provider.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/tracer_provider'>;
}
declare module '@opentelemetry/api/build/esm/trace/tracer.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/trace/tracer'>;
}
declare module '@opentelemetry/api/build/esm/version.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/esm/version'>;
}
declare module '@opentelemetry/api/build/src/api/context.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/api/context'>;
}
declare module '@opentelemetry/api/build/src/api/diag.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/api/diag'>;
}
declare module '@opentelemetry/api/build/src/api/propagation.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/api/propagation'>;
}
declare module '@opentelemetry/api/build/src/api/trace.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/api/trace'>;
}
declare module '@opentelemetry/api/build/src/baggage/context-helpers.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/baggage/context-helpers'>;
}
declare module '@opentelemetry/api/build/src/baggage/internal/baggage-impl.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/baggage/internal/baggage-impl'>;
}
declare module '@opentelemetry/api/build/src/baggage/internal/symbol.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/baggage/internal/symbol'>;
}
declare module '@opentelemetry/api/build/src/baggage/types.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/baggage/types'>;
}
declare module '@opentelemetry/api/build/src/baggage/utils.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/baggage/utils'>;
}
declare module '@opentelemetry/api/build/src/common/Exception.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/common/Exception'>;
}
declare module '@opentelemetry/api/build/src/common/Time.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/common/Time'>;
}
declare module '@opentelemetry/api/build/src/context/context.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/context/context'>;
}
declare module '@opentelemetry/api/build/src/context/NoopContextManager.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/context/NoopContextManager'>;
}
declare module '@opentelemetry/api/build/src/context/types.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/context/types'>;
}
declare module '@opentelemetry/api/build/src/diag/ComponentLogger.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/diag/ComponentLogger'>;
}
declare module '@opentelemetry/api/build/src/diag/consoleLogger.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/diag/consoleLogger'>;
}
declare module '@opentelemetry/api/build/src/diag/index' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/diag'>;
}
declare module '@opentelemetry/api/build/src/diag/index.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/diag'>;
}
declare module '@opentelemetry/api/build/src/diag/internal/logLevelLogger.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/diag/internal/logLevelLogger'>;
}
declare module '@opentelemetry/api/build/src/diag/internal/noopLogger.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/diag/internal/noopLogger'>;
}
declare module '@opentelemetry/api/build/src/diag/types.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/diag/types'>;
}
declare module '@opentelemetry/api/build/src/index' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src'>;
}
declare module '@opentelemetry/api/build/src/index.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src'>;
}
declare module '@opentelemetry/api/build/src/internal/global-utils.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/internal/global-utils'>;
}
declare module '@opentelemetry/api/build/src/internal/semver.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/internal/semver'>;
}
declare module '@opentelemetry/api/build/src/platform/browser/globalThis.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/platform/browser/globalThis'>;
}
declare module '@opentelemetry/api/build/src/platform/browser/index' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/platform/browser'>;
}
declare module '@opentelemetry/api/build/src/platform/browser/index.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/platform/browser'>;
}
declare module '@opentelemetry/api/build/src/platform/index' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/platform'>;
}
declare module '@opentelemetry/api/build/src/platform/index.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/platform'>;
}
declare module '@opentelemetry/api/build/src/platform/node/globalThis.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/platform/node/globalThis'>;
}
declare module '@opentelemetry/api/build/src/platform/node/index' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/platform/node'>;
}
declare module '@opentelemetry/api/build/src/platform/node/index.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/platform/node'>;
}
declare module '@opentelemetry/api/build/src/propagation/NoopTextMapPropagator.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/propagation/NoopTextMapPropagator'>;
}
declare module '@opentelemetry/api/build/src/propagation/TextMapPropagator.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/propagation/TextMapPropagator'>;
}
declare module '@opentelemetry/api/build/src/trace/attributes.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/attributes'>;
}
declare module '@opentelemetry/api/build/src/trace/context-utils.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/context-utils'>;
}
declare module '@opentelemetry/api/build/src/trace/link.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/link'>;
}
declare module '@opentelemetry/api/build/src/trace/NonRecordingSpan.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/NonRecordingSpan'>;
}
declare module '@opentelemetry/api/build/src/trace/NoopTracer.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/NoopTracer'>;
}
declare module '@opentelemetry/api/build/src/trace/NoopTracerProvider.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/NoopTracerProvider'>;
}
declare module '@opentelemetry/api/build/src/trace/ProxyTracer.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/ProxyTracer'>;
}
declare module '@opentelemetry/api/build/src/trace/ProxyTracerProvider.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/ProxyTracerProvider'>;
}
declare module '@opentelemetry/api/build/src/trace/Sampler.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/Sampler'>;
}
declare module '@opentelemetry/api/build/src/trace/SamplingResult.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/SamplingResult'>;
}
declare module '@opentelemetry/api/build/src/trace/span_context.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/span_context'>;
}
declare module '@opentelemetry/api/build/src/trace/span_kind.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/span_kind'>;
}
declare module '@opentelemetry/api/build/src/trace/span.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/span'>;
}
declare module '@opentelemetry/api/build/src/trace/spancontext-utils.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/spancontext-utils'>;
}
declare module '@opentelemetry/api/build/src/trace/SpanOptions.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/SpanOptions'>;
}
declare module '@opentelemetry/api/build/src/trace/status.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/status'>;
}
declare module '@opentelemetry/api/build/src/trace/trace_flags.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/trace_flags'>;
}
declare module '@opentelemetry/api/build/src/trace/trace_state.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/trace_state'>;
}
declare module '@opentelemetry/api/build/src/trace/tracer_provider.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/tracer_provider'>;
}
declare module '@opentelemetry/api/build/src/trace/tracer.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/trace/tracer'>;
}
declare module '@opentelemetry/api/build/src/version.js' {
  declare module.exports: $Exports<'@opentelemetry/api/build/src/version'>;
}
