// flow-typed signature: 9a1cd78a6e74120ffa39f6e399f0e1b4
// flow-typed version: <<STUB>>/grant_v5.4.21/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grant'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grant' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grant/grant' {
  declare module.exports: any;
}

declare module 'grant/lib/client' {
  declare module.exports: any;
}

declare module 'grant/lib/config' {
  declare module.exports: any;
}

declare module 'grant/lib/flow/oauth1' {
  declare module.exports: any;
}

declare module 'grant/lib/flow/oauth2' {
  declare module.exports: any;
}

declare module 'grant/lib/grant' {
  declare module.exports: any;
}

declare module 'grant/lib/handler/aws' {
  declare module.exports: any;
}

declare module 'grant/lib/handler/azure' {
  declare module.exports: any;
}

declare module 'grant/lib/handler/curveball' {
  declare module.exports: any;
}

declare module 'grant/lib/handler/express-4' {
  declare module.exports: any;
}

declare module 'grant/lib/handler/fastify' {
  declare module.exports: any;
}

declare module 'grant/lib/handler/gcloud' {
  declare module.exports: any;
}

declare module 'grant/lib/handler/hapi-16' {
  declare module.exports: any;
}

declare module 'grant/lib/handler/hapi-17' {
  declare module.exports: any;
}

declare module 'grant/lib/handler/koa-1' {
  declare module.exports: any;
}

declare module 'grant/lib/handler/koa-2' {
  declare module.exports: any;
}

declare module 'grant/lib/handler/node' {
  declare module.exports: any;
}

declare module 'grant/lib/handler/vercel' {
  declare module.exports: any;
}

declare module 'grant/lib/oidc' {
  declare module.exports: any;
}

declare module 'grant/lib/profile' {
  declare module.exports: any;
}

declare module 'grant/lib/request' {
  declare module.exports: any;
}

declare module 'grant/lib/response' {
  declare module.exports: any;
}

declare module 'grant/lib/session' {
  declare module.exports: any;
}

declare module 'grant/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grant/grant.js' {
  declare module.exports: $Exports<'grant/grant'>;
}
declare module 'grant/lib/client.js' {
  declare module.exports: $Exports<'grant/lib/client'>;
}
declare module 'grant/lib/config.js' {
  declare module.exports: $Exports<'grant/lib/config'>;
}
declare module 'grant/lib/flow/oauth1.js' {
  declare module.exports: $Exports<'grant/lib/flow/oauth1'>;
}
declare module 'grant/lib/flow/oauth2.js' {
  declare module.exports: $Exports<'grant/lib/flow/oauth2'>;
}
declare module 'grant/lib/grant.js' {
  declare module.exports: $Exports<'grant/lib/grant'>;
}
declare module 'grant/lib/handler/aws.js' {
  declare module.exports: $Exports<'grant/lib/handler/aws'>;
}
declare module 'grant/lib/handler/azure.js' {
  declare module.exports: $Exports<'grant/lib/handler/azure'>;
}
declare module 'grant/lib/handler/curveball.js' {
  declare module.exports: $Exports<'grant/lib/handler/curveball'>;
}
declare module 'grant/lib/handler/express-4.js' {
  declare module.exports: $Exports<'grant/lib/handler/express-4'>;
}
declare module 'grant/lib/handler/fastify.js' {
  declare module.exports: $Exports<'grant/lib/handler/fastify'>;
}
declare module 'grant/lib/handler/gcloud.js' {
  declare module.exports: $Exports<'grant/lib/handler/gcloud'>;
}
declare module 'grant/lib/handler/hapi-16.js' {
  declare module.exports: $Exports<'grant/lib/handler/hapi-16'>;
}
declare module 'grant/lib/handler/hapi-17.js' {
  declare module.exports: $Exports<'grant/lib/handler/hapi-17'>;
}
declare module 'grant/lib/handler/koa-1.js' {
  declare module.exports: $Exports<'grant/lib/handler/koa-1'>;
}
declare module 'grant/lib/handler/koa-2.js' {
  declare module.exports: $Exports<'grant/lib/handler/koa-2'>;
}
declare module 'grant/lib/handler/node.js' {
  declare module.exports: $Exports<'grant/lib/handler/node'>;
}
declare module 'grant/lib/handler/vercel.js' {
  declare module.exports: $Exports<'grant/lib/handler/vercel'>;
}
declare module 'grant/lib/oidc.js' {
  declare module.exports: $Exports<'grant/lib/oidc'>;
}
declare module 'grant/lib/profile.js' {
  declare module.exports: $Exports<'grant/lib/profile'>;
}
declare module 'grant/lib/request.js' {
  declare module.exports: $Exports<'grant/lib/request'>;
}
declare module 'grant/lib/response.js' {
  declare module.exports: $Exports<'grant/lib/response'>;
}
declare module 'grant/lib/session.js' {
  declare module.exports: $Exports<'grant/lib/session'>;
}
declare module 'grant/lib/util.js' {
  declare module.exports: $Exports<'grant/lib/util'>;
}
