// flow-typed signature: f3e6d3ff17813fa831aa7c61fbb33cd8
// flow-typed version: <<STUB>>/koa-helmet_v6.1.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-helmet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-helmet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-helmet/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'koa-helmet/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'koa-helmet/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'koa-helmet/lib/koa-helmet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-helmet/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'koa-helmet/coverage/lcov-report/block-navigation'>;
}
declare module 'koa-helmet/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'koa-helmet/coverage/lcov-report/prettify'>;
}
declare module 'koa-helmet/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'koa-helmet/coverage/lcov-report/sorter'>;
}
declare module 'koa-helmet/lib/koa-helmet.js' {
  declare module.exports: $Exports<'koa-helmet/lib/koa-helmet'>;
}
