// flow-typed signature: 90d7df7987402c18b124c6ecd1fcade8
// flow-typed version: <<STUB>>/koa-oas3_v2.5.0/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-oas3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-oas3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-oas3/lib/config' {
  declare module.exports: any;
}

declare module 'koa-oas3/lib' {
  declare module.exports: any;
}

declare module 'koa-oas3/lib/openapi-ui' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-oas3/lib/config.js' {
  declare module.exports: $Exports<'koa-oas3/lib/config'>;
}
declare module 'koa-oas3/lib/index' {
  declare module.exports: $Exports<'koa-oas3/lib'>;
}
declare module 'koa-oas3/lib/index.js' {
  declare module.exports: $Exports<'koa-oas3/lib'>;
}
declare module 'koa-oas3/lib/openapi-ui.js' {
  declare module.exports: $Exports<'koa-oas3/lib/openapi-ui'>;
}
