// flow-typed signature: c6936274c28c3befc3609f118f379284
// flow-typed version: <<STUB>>/koa-csrf_v3.0.8/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-csrf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-csrf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-csrf/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-csrf/lib/index' {
  declare module.exports: $Exports<'koa-csrf/lib'>;
}
declare module 'koa-csrf/lib/index.js' {
  declare module.exports: $Exports<'koa-csrf/lib'>;
}
