// flow-typed signature: 503f32614999f9a0de08ce3993f82912
// flow-typed version: <<STUB>>/koa-sslify_v5.0.0/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-sslify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-sslify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-sslify/test/koa-sslify-azure-test' {
  declare module.exports: any;
}

declare module 'koa-sslify/test/koa-sslify-custom-proto-test' {
  declare module.exports: any;
}

declare module 'koa-sslify/test/koa-sslify-forwarded-test' {
  declare module.exports: any;
}

declare module 'koa-sslify/test/koa-sslify-proto-test' {
  declare module.exports: any;
}

declare module 'koa-sslify/test/koa-sslify-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-sslify/index' {
  declare module.exports: $Exports<'koa-sslify'>;
}
declare module 'koa-sslify/index.js' {
  declare module.exports: $Exports<'koa-sslify'>;
}
declare module 'koa-sslify/test/koa-sslify-azure-test.js' {
  declare module.exports: $Exports<'koa-sslify/test/koa-sslify-azure-test'>;
}
declare module 'koa-sslify/test/koa-sslify-custom-proto-test.js' {
  declare module.exports: $Exports<'koa-sslify/test/koa-sslify-custom-proto-test'>;
}
declare module 'koa-sslify/test/koa-sslify-forwarded-test.js' {
  declare module.exports: $Exports<'koa-sslify/test/koa-sslify-forwarded-test'>;
}
declare module 'koa-sslify/test/koa-sslify-proto-test.js' {
  declare module.exports: $Exports<'koa-sslify/test/koa-sslify-proto-test'>;
}
declare module 'koa-sslify/test/koa-sslify-test.js' {
  declare module.exports: $Exports<'koa-sslify/test/koa-sslify-test'>;
}
