// flow-typed signature: 9e4e74d1c4625597f6b09a39c4587850
// flow-typed version: <<STUB>>/yaml-eslint-parser_v0.5.0/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yaml-eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yaml-eslint-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yaml-eslint-parser/lib/ast' {
  declare module.exports: any;
}

declare module 'yaml-eslint-parser/lib/context' {
  declare module.exports: any;
}

declare module 'yaml-eslint-parser/lib/convert' {
  declare module.exports: any;
}

declare module 'yaml-eslint-parser/lib/errors' {
  declare module.exports: any;
}

declare module 'yaml-eslint-parser/lib' {
  declare module.exports: any;
}

declare module 'yaml-eslint-parser/lib/parser' {
  declare module.exports: any;
}

declare module 'yaml-eslint-parser/lib/tags/commons' {
  declare module.exports: any;
}

declare module 'yaml-eslint-parser/lib/tags' {
  declare module.exports: any;
}

declare module 'yaml-eslint-parser/lib/tags/tags1.1' {
  declare module.exports: any;
}

declare module 'yaml-eslint-parser/lib/tags/tags1.2' {
  declare module.exports: any;
}

declare module 'yaml-eslint-parser/lib/traverse' {
  declare module.exports: any;
}

declare module 'yaml-eslint-parser/lib/utils' {
  declare module.exports: any;
}

declare module 'yaml-eslint-parser/lib/visitor-keys' {
  declare module.exports: any;
}

declare module 'yaml-eslint-parser/lib/yaml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yaml-eslint-parser/lib/ast.js' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib/ast'>;
}
declare module 'yaml-eslint-parser/lib/context.js' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib/context'>;
}
declare module 'yaml-eslint-parser/lib/convert.js' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib/convert'>;
}
declare module 'yaml-eslint-parser/lib/errors.js' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib/errors'>;
}
declare module 'yaml-eslint-parser/lib/index' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib'>;
}
declare module 'yaml-eslint-parser/lib/index.js' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib'>;
}
declare module 'yaml-eslint-parser/lib/parser.js' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib/parser'>;
}
declare module 'yaml-eslint-parser/lib/tags/commons.js' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib/tags/commons'>;
}
declare module 'yaml-eslint-parser/lib/tags/index' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib/tags'>;
}
declare module 'yaml-eslint-parser/lib/tags/index.js' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib/tags'>;
}
declare module 'yaml-eslint-parser/lib/tags/tags1.1.js' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib/tags/tags1.1'>;
}
declare module 'yaml-eslint-parser/lib/tags/tags1.2.js' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib/tags/tags1.2'>;
}
declare module 'yaml-eslint-parser/lib/traverse.js' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib/traverse'>;
}
declare module 'yaml-eslint-parser/lib/utils.js' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib/utils'>;
}
declare module 'yaml-eslint-parser/lib/visitor-keys.js' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib/visitor-keys'>;
}
declare module 'yaml-eslint-parser/lib/yaml.js' {
  declare module.exports: $Exports<'yaml-eslint-parser/lib/yaml'>;
}
