// flow-typed signature: 39b8c8904b3174ff570b30dd895970ae
// flow-typed version: <<STUB>>/@babel/eslint-parser_v7.14.7/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
