// flow-typed signature: 0dad374780a7546d375a82e0229487f0
// flow-typed version: <<STUB>>/@babel/eslint-parser_v7.15.8/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
