// flow-typed signature: 9e1806dcdaf66f6e16b6876ace607ed0
// flow-typed version: <<STUB>>/picomatch_v2.3.1/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'picomatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'picomatch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'picomatch/lib/constants' {
  declare module.exports: any;
}

declare module 'picomatch/lib/parse' {
  declare module.exports: any;
}

declare module 'picomatch/lib/picomatch' {
  declare module.exports: any;
}

declare module 'picomatch/lib/scan' {
  declare module.exports: any;
}

declare module 'picomatch/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'picomatch/index' {
  declare module.exports: $Exports<'picomatch'>;
}
declare module 'picomatch/index.js' {
  declare module.exports: $Exports<'picomatch'>;
}
declare module 'picomatch/lib/constants.js' {
  declare module.exports: $Exports<'picomatch/lib/constants'>;
}
declare module 'picomatch/lib/parse.js' {
  declare module.exports: $Exports<'picomatch/lib/parse'>;
}
declare module 'picomatch/lib/picomatch.js' {
  declare module.exports: $Exports<'picomatch/lib/picomatch'>;
}
declare module 'picomatch/lib/scan.js' {
  declare module.exports: $Exports<'picomatch/lib/scan'>;
}
declare module 'picomatch/lib/utils.js' {
  declare module.exports: $Exports<'picomatch/lib/utils'>;
}
