# @todo: add rules from: https://www.npmjs.com/package/eslint-plugin-flowtype

env: # @see https://eslint.org/docs/user-guide/configuring/language-options
  es2021: true
  shared-node-browser: true
  worker: true
  serviceworker: true
parser: '@babel/eslint-parser'
parserOptions: # @see https://www.npmjs.com/package/@babel/eslint-parser
  requireConfigFile: false
  sourceType: module
  ecmaFeatures:
    jsx: true
  # babelOptions:
    # configFile: 'lib/babel.config.cjs' # shits broken? throws parser error cant find
extends:
  - eslint:all
  - standard
  - plugin:import/recommended
  - plugin:node/recommended
  - plugin:promise/recommended
  - plugin:react/all
  - plugin:react-hooks/recommended
plugins:
  - '@babel'
  - flow
settings:
  react:
    createClass: createReactClass
    pragma: React
    fragment: Fragment
    version: detect
  flowtype:
    onlyFilesWithFlowAnnotation: true
rules:
  # great rules here
  '@babel/new-cap': 'error'
  '@babel/no-invalid-this': 'error'
  '@babel/no-unused-expressions': 'error'
  '@babel/object-curly-spacing': ['error', 'always']
  function-call-argument-newline: ['error', 'consistent']
  jsx-quotes: ['error', 'prefer-single']
  no-multiple-empty-lines: 'error'
  no-throw-literal: 'error'
  prefer-named-capture-group: 'off' # performance
  prefer-object-spread: 'error'
  react-hooks/exhaustive-deps: 'warn'
  react-hooks/rules-of-hooks: 'error'
  react/display-name: 'error'
  react/forbid-component-props: ['error', {forbid: ['reactsucks', 'angularisgreat']}]
  react/jsx-indent-props: ['error', 2]
  react/jsx-indent: ['error', 2]
  react/jsx-max-depth: ['error', {max: 5}]
  react/jsx-max-props-per-line: ['error', {maximum: 3, when: multiline}]
  react/jsx-no-literals: 'warn'
  react/jsx-one-expression-per-line: ['error', {allow: single-child}]
  sort-imports: 'error' # I hate serching a list for shit
  sort-keys: 'error' # i hate searchig a list for shit
  max-lines-per-function:
    - error
    - skipBlankLines: true
      skipComments: true

  # dumb fkn rules here
  arrow-parens: 'off'
  capitalized-comments: 'off'
  comma-dangle: 'off' # love trailing commas
  id-length: 'off' # we support junior devs without hampering others
  line-comment-position: 'off'
  multiline-comment-style: 'off'
  no-inline-comments: 'off'
  no-ternary: 'off'
  react/jsx-filename-extension: 'off'
  react/prop-types: 'off' # not a fan, dont care if you are
  semi: 'off' # love ending semi - read this https://eslint.org/docs/rules/semi
  react/jsx-props-no-spreading: 'off'
  react/destructuring-assignment: 'off'

  # doesnt seem to work right - but would be great if it did
  node/no-unpublished-import: 'off'



