env:
  browser: true
  es2021: true
  node: true
extends:
  - standard
  - babel
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  comma-dangle: 'off' # big fan
  react/prop-types: 'off' # not a fan
  react/display-name: 'error'
  react-hooks/rules-of-hooks: 'error'
  react-hooks/exhaustive-deps: 'warn'
