// flow-typed signature: 03705ee14ca570cb10cd1d2c45a379fc
// flow-typed version: <<STUB>>/@types/download_v8.0.1/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/download'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/download' {
  declare module.exports: any;
}
