// flow-typed signature: d407b8321fa88e9d4988c4135a646fb1
// flow-typed version: <<STUB>>/@swc/cli_v0.1.46/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@swc/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@swc/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@swc/cli/bin/spack' {
  declare module.exports: any;
}

declare module '@swc/cli/bin/swc' {
  declare module.exports: any;
}

declare module '@swc/cli/lib/spack' {
  declare module.exports: any;
}

declare module '@swc/cli/lib/spack/options' {
  declare module.exports: any;
}

declare module '@swc/cli/lib/swc/__mocks__/fs' {
  declare module.exports: any;
}

declare module '@swc/cli/lib/swc/__tests__/compile.test' {
  declare module.exports: any;
}

declare module '@swc/cli/lib/swc/__tests__/sources.test' {
  declare module.exports: any;
}

declare module '@swc/cli/lib/swc/__tests__/utils.test' {
  declare module.exports: any;
}

declare module '@swc/cli/lib/swc/compile' {
  declare module.exports: any;
}

declare module '@swc/cli/lib/swc/constants' {
  declare module.exports: any;
}

declare module '@swc/cli/lib/swc/dir' {
  declare module.exports: any;
}

declare module '@swc/cli/lib/swc/file' {
  declare module.exports: any;
}

declare module '@swc/cli/lib/swc' {
  declare module.exports: any;
}

declare module '@swc/cli/lib/swc/options' {
  declare module.exports: any;
}

declare module '@swc/cli/lib/swc/sources' {
  declare module.exports: any;
}

declare module '@swc/cli/lib/swc/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@swc/cli/bin/spack.js' {
  declare module.exports: $Exports<'@swc/cli/bin/spack'>;
}
declare module '@swc/cli/bin/swc.js' {
  declare module.exports: $Exports<'@swc/cli/bin/swc'>;
}
declare module '@swc/cli/lib/spack/index' {
  declare module.exports: $Exports<'@swc/cli/lib/spack'>;
}
declare module '@swc/cli/lib/spack/index.js' {
  declare module.exports: $Exports<'@swc/cli/lib/spack'>;
}
declare module '@swc/cli/lib/spack/options.js' {
  declare module.exports: $Exports<'@swc/cli/lib/spack/options'>;
}
declare module '@swc/cli/lib/swc/__mocks__/fs.js' {
  declare module.exports: $Exports<'@swc/cli/lib/swc/__mocks__/fs'>;
}
declare module '@swc/cli/lib/swc/__tests__/compile.test.js' {
  declare module.exports: $Exports<'@swc/cli/lib/swc/__tests__/compile.test'>;
}
declare module '@swc/cli/lib/swc/__tests__/sources.test.js' {
  declare module.exports: $Exports<'@swc/cli/lib/swc/__tests__/sources.test'>;
}
declare module '@swc/cli/lib/swc/__tests__/utils.test.js' {
  declare module.exports: $Exports<'@swc/cli/lib/swc/__tests__/utils.test'>;
}
declare module '@swc/cli/lib/swc/compile.js' {
  declare module.exports: $Exports<'@swc/cli/lib/swc/compile'>;
}
declare module '@swc/cli/lib/swc/constants.js' {
  declare module.exports: $Exports<'@swc/cli/lib/swc/constants'>;
}
declare module '@swc/cli/lib/swc/dir.js' {
  declare module.exports: $Exports<'@swc/cli/lib/swc/dir'>;
}
declare module '@swc/cli/lib/swc/file.js' {
  declare module.exports: $Exports<'@swc/cli/lib/swc/file'>;
}
declare module '@swc/cli/lib/swc/index' {
  declare module.exports: $Exports<'@swc/cli/lib/swc'>;
}
declare module '@swc/cli/lib/swc/index.js' {
  declare module.exports: $Exports<'@swc/cli/lib/swc'>;
}
declare module '@swc/cli/lib/swc/options.js' {
  declare module.exports: $Exports<'@swc/cli/lib/swc/options'>;
}
declare module '@swc/cli/lib/swc/sources.js' {
  declare module.exports: $Exports<'@swc/cli/lib/swc/sources'>;
}
declare module '@swc/cli/lib/swc/util.js' {
  declare module.exports: $Exports<'@swc/cli/lib/swc/util'>;
}
