// was originally client/lib/webpack.dev.config.mjs
// TODO: use to have dependency on envproto

import baseWebpackConfig from './base.webpack.config.mjs';
import HtmlWebpackPlugin from 'html-webpack-plugin';
import webpack from 'webpack';

const r = (t, msg = 'is required') => { throw new Error(`${t}: ${msg}`); };

export default function reactDevWebpackConfig({
  entry = r('entry: Array'),
  htmlOptions = r('htmlOptions'),

  pack = {},
  pathDist = pack.pathDist || r('pathDist'),
  pathSrc = pack.pathSrc || r('pathSrc'),

  ...overrides
}) {
  if (!Array.isArray(entry)) r('entry: Array');

  return baseWebpackConfig({
    entry,
    entryUnshift: [
      'react-devtools',
      'webpack-hot-middleware-2/client'
    ],
    pack,
    pathDist,
    pathSrc,
    plugins: [
      new webpack.HotModuleReplacementPlugin(),

      new HtmlWebpackPlugin({
        inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
        ...htmlOptions,
      }),

      // new ScriptExtHtmlWebpackPlugin({
      //   module: /(workers|sw)/,
      // }),
    ],
    ...overrides,
  });
}
