// flow-typed signature: c41ff0e8ddff593ba52e598952958ea6
// flow-typed version: <<STUB>>/@tinyhttp/etag_v2.0.3/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tinyhttp/etag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tinyhttp/etag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tinyhttp/etag/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tinyhttp/etag/dist/index' {
  declare module.exports: $Exports<'@tinyhttp/etag/dist'>;
}
declare module '@tinyhttp/etag/dist/index.js' {
  declare module.exports: $Exports<'@tinyhttp/etag/dist'>;
}
