// flow-typed signature: 74316b32a470fc67624e76c8d8253441
// flow-typed version: <<STUB>>/jsdoc-to-markdown_v7.0.1/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdoc-to-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdoc-to-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdoc-to-markdown/bin/cli' {
  declare module.exports: any;
}

declare module 'jsdoc-to-markdown/lib/cli-data' {
  declare module.exports: any;
}

declare module 'jsdoc-to-markdown/lib/dmd-options' {
  declare module.exports: any;
}

declare module 'jsdoc-to-markdown/lib/jsdoc-options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdoc-to-markdown/bin/cli.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown/bin/cli'>;
}
declare module 'jsdoc-to-markdown/index' {
  declare module.exports: $Exports<'jsdoc-to-markdown'>;
}
declare module 'jsdoc-to-markdown/index.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown'>;
}
declare module 'jsdoc-to-markdown/lib/cli-data.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown/lib/cli-data'>;
}
declare module 'jsdoc-to-markdown/lib/dmd-options.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown/lib/dmd-options'>;
}
declare module 'jsdoc-to-markdown/lib/jsdoc-options.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown/lib/jsdoc-options'>;
}
