// flow-typed signature: 5c5a3a7572a855fe7ea2d6678b2c211d
// flow-typed version: <<STUB>>/jsonfile_v6.1.0/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonfile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonfile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonfile/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonfile/index' {
  declare module.exports: $Exports<'jsonfile'>;
}
declare module 'jsonfile/index.js' {
  declare module.exports: $Exports<'jsonfile'>;
}
declare module 'jsonfile/utils.js' {
  declare module.exports: $Exports<'jsonfile/utils'>;
}
