// flow-typed signature: 6b026d8e5fcc86e0bc2e9deb430bf62e
// flow-typed version: <<STUB>>/tap-spec_v2.2.2/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tap-spec'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tap-spec' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tap-spec/bin/cmd' {
  declare module.exports: any;
}

declare module 'tap-spec/test/e2e' {
  declare module.exports: any;
}

declare module 'tap-spec/test/unit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tap-spec/bin/cmd.js' {
  declare module.exports: $Exports<'tap-spec/bin/cmd'>;
}
declare module 'tap-spec/index' {
  declare module.exports: $Exports<'tap-spec'>;
}
declare module 'tap-spec/index.js' {
  declare module.exports: $Exports<'tap-spec'>;
}
declare module 'tap-spec/test/e2e/index' {
  declare module.exports: $Exports<'tap-spec/test/e2e'>;
}
declare module 'tap-spec/test/e2e/index.js' {
  declare module.exports: $Exports<'tap-spec/test/e2e'>;
}
declare module 'tap-spec/test/unit/index' {
  declare module.exports: $Exports<'tap-spec/test/unit'>;
}
declare module 'tap-spec/test/unit/index.js' {
  declare module.exports: $Exports<'tap-spec/test/unit'>;
}
