// flow-typed signature: 79b341889fcec0a22fc82d161df11993
// flow-typed version: <<STUB>>/download_v8.0.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'download'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'download' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'download/index' {
  declare module.exports: $Exports<'download'>;
}
declare module 'download/index.js' {
  declare module.exports: $Exports<'download'>;
}
