// flow-typed signature: b2d7200b08da20023f7177fcd5de999b
// flow-typed version: <<STUB>>/safe-compare_v1.1.4/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'safe-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'safe-compare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'safe-compare/index' {
  declare module.exports: $Exports<'safe-compare'>;
}
declare module 'safe-compare/index.js' {
  declare module.exports: $Exports<'safe-compare'>;
}
