// flow-typed signature: 6c479698dba04f502e1aa1823d432de5
// flow-typed version: <<STUB>>/web-ext-translator_v4.0.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web-ext-translator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web-ext-translator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web-ext-translator/dist/cli' {
  declare module.exports: any;
}

declare module 'web-ext-translator/dist/docs/src.8d6a7a68' {
  declare module.exports: any;
}

declare module 'web-ext-translator/dist/main' {
  declare module.exports: any;
}

declare module 'web-ext-translator/dist/preload' {
  declare module.exports: any;
}

declare module 'web-ext-translator/dist/searchPreload' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web-ext-translator/dist/cli.js' {
  declare module.exports: $Exports<'web-ext-translator/dist/cli'>;
}
declare module 'web-ext-translator/dist/docs/src.8d6a7a68.js' {
  declare module.exports: $Exports<'web-ext-translator/dist/docs/src.8d6a7a68'>;
}
declare module 'web-ext-translator/dist/main.js' {
  declare module.exports: $Exports<'web-ext-translator/dist/main'>;
}
declare module 'web-ext-translator/dist/preload.js' {
  declare module.exports: $Exports<'web-ext-translator/dist/preload'>;
}
declare module 'web-ext-translator/dist/searchPreload.js' {
  declare module.exports: $Exports<'web-ext-translator/dist/searchPreload'>;
}
