// flow-typed signature: 02fb6cf1a05858ae18d405cfbdb4bdc5
// flow-typed version: <<STUB>>/web-ext_v~6.4.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web-ext'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web-ext' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web-ext/dist/web-ext' {
  declare module.exports: any;
}

declare module 'web-ext/src/cmd/build' {
  declare module.exports: any;
}

declare module 'web-ext/src/cmd/docs' {
  declare module.exports: any;
}

declare module 'web-ext/src/cmd' {
  declare module.exports: any;
}

declare module 'web-ext/src/cmd/lint' {
  declare module.exports: any;
}

declare module 'web-ext/src/cmd/run' {
  declare module.exports: any;
}

declare module 'web-ext/src/cmd/sign' {
  declare module.exports: any;
}

declare module 'web-ext/src/config' {
  declare module.exports: any;
}

declare module 'web-ext/src/errors' {
  declare module.exports: any;
}

declare module 'web-ext/src/extension-runners/base' {
  declare module.exports: any;
}

declare module 'web-ext/src/extension-runners/chromium' {
  declare module.exports: any;
}

declare module 'web-ext/src/extension-runners/firefox-android' {
  declare module.exports: any;
}

declare module 'web-ext/src/extension-runners/firefox-desktop' {
  declare module.exports: any;
}

declare module 'web-ext/src/extension-runners' {
  declare module.exports: any;
}

declare module 'web-ext/src/firefox' {
  declare module.exports: any;
}

declare module 'web-ext/src/firefox/package-identifiers' {
  declare module.exports: any;
}

declare module 'web-ext/src/firefox/preferences' {
  declare module.exports: any;
}

declare module 'web-ext/src/firefox/rdp-client' {
  declare module.exports: any;
}

declare module 'web-ext/src/firefox/remote' {
  declare module.exports: any;
}

declare module 'web-ext/src/main' {
  declare module.exports: any;
}

declare module 'web-ext/src/program' {
  declare module.exports: any;
}

declare module 'web-ext/src/util/adb' {
  declare module.exports: any;
}

declare module 'web-ext/src/util/artifacts' {
  declare module.exports: any;
}

declare module 'web-ext/src/util/desktop-notifier' {
  declare module.exports: any;
}

declare module 'web-ext/src/util/file-exists' {
  declare module.exports: any;
}

declare module 'web-ext/src/util/file-filter' {
  declare module.exports: any;
}

declare module 'web-ext/src/util/is-directory' {
  declare module.exports: any;
}

declare module 'web-ext/src/util/logger' {
  declare module.exports: any;
}

declare module 'web-ext/src/util/manifest' {
  declare module.exports: any;
}

declare module 'web-ext/src/util/promisify' {
  declare module.exports: any;
}

declare module 'web-ext/src/util/stdin' {
  declare module.exports: any;
}

declare module 'web-ext/src/util/temp-dir' {
  declare module.exports: any;
}

declare module 'web-ext/src/util/updates' {
  declare module.exports: any;
}

declare module 'web-ext/src/watcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web-ext/dist/web-ext.js' {
  declare module.exports: $Exports<'web-ext/dist/web-ext'>;
}
declare module 'web-ext/src/cmd/build.js' {
  declare module.exports: $Exports<'web-ext/src/cmd/build'>;
}
declare module 'web-ext/src/cmd/docs.js' {
  declare module.exports: $Exports<'web-ext/src/cmd/docs'>;
}
declare module 'web-ext/src/cmd/index' {
  declare module.exports: $Exports<'web-ext/src/cmd'>;
}
declare module 'web-ext/src/cmd/index.js' {
  declare module.exports: $Exports<'web-ext/src/cmd'>;
}
declare module 'web-ext/src/cmd/lint.js' {
  declare module.exports: $Exports<'web-ext/src/cmd/lint'>;
}
declare module 'web-ext/src/cmd/run.js' {
  declare module.exports: $Exports<'web-ext/src/cmd/run'>;
}
declare module 'web-ext/src/cmd/sign.js' {
  declare module.exports: $Exports<'web-ext/src/cmd/sign'>;
}
declare module 'web-ext/src/config.js' {
  declare module.exports: $Exports<'web-ext/src/config'>;
}
declare module 'web-ext/src/errors.js' {
  declare module.exports: $Exports<'web-ext/src/errors'>;
}
declare module 'web-ext/src/extension-runners/base.js' {
  declare module.exports: $Exports<'web-ext/src/extension-runners/base'>;
}
declare module 'web-ext/src/extension-runners/chromium.js' {
  declare module.exports: $Exports<'web-ext/src/extension-runners/chromium'>;
}
declare module 'web-ext/src/extension-runners/firefox-android.js' {
  declare module.exports: $Exports<'web-ext/src/extension-runners/firefox-android'>;
}
declare module 'web-ext/src/extension-runners/firefox-desktop.js' {
  declare module.exports: $Exports<'web-ext/src/extension-runners/firefox-desktop'>;
}
declare module 'web-ext/src/extension-runners/index' {
  declare module.exports: $Exports<'web-ext/src/extension-runners'>;
}
declare module 'web-ext/src/extension-runners/index.js' {
  declare module.exports: $Exports<'web-ext/src/extension-runners'>;
}
declare module 'web-ext/src/firefox/index' {
  declare module.exports: $Exports<'web-ext/src/firefox'>;
}
declare module 'web-ext/src/firefox/index.js' {
  declare module.exports: $Exports<'web-ext/src/firefox'>;
}
declare module 'web-ext/src/firefox/package-identifiers.js' {
  declare module.exports: $Exports<'web-ext/src/firefox/package-identifiers'>;
}
declare module 'web-ext/src/firefox/preferences.js' {
  declare module.exports: $Exports<'web-ext/src/firefox/preferences'>;
}
declare module 'web-ext/src/firefox/rdp-client.js' {
  declare module.exports: $Exports<'web-ext/src/firefox/rdp-client'>;
}
declare module 'web-ext/src/firefox/remote.js' {
  declare module.exports: $Exports<'web-ext/src/firefox/remote'>;
}
declare module 'web-ext/src/main.js' {
  declare module.exports: $Exports<'web-ext/src/main'>;
}
declare module 'web-ext/src/program.js' {
  declare module.exports: $Exports<'web-ext/src/program'>;
}
declare module 'web-ext/src/util/adb.js' {
  declare module.exports: $Exports<'web-ext/src/util/adb'>;
}
declare module 'web-ext/src/util/artifacts.js' {
  declare module.exports: $Exports<'web-ext/src/util/artifacts'>;
}
declare module 'web-ext/src/util/desktop-notifier.js' {
  declare module.exports: $Exports<'web-ext/src/util/desktop-notifier'>;
}
declare module 'web-ext/src/util/file-exists.js' {
  declare module.exports: $Exports<'web-ext/src/util/file-exists'>;
}
declare module 'web-ext/src/util/file-filter.js' {
  declare module.exports: $Exports<'web-ext/src/util/file-filter'>;
}
declare module 'web-ext/src/util/is-directory.js' {
  declare module.exports: $Exports<'web-ext/src/util/is-directory'>;
}
declare module 'web-ext/src/util/logger.js' {
  declare module.exports: $Exports<'web-ext/src/util/logger'>;
}
declare module 'web-ext/src/util/manifest.js' {
  declare module.exports: $Exports<'web-ext/src/util/manifest'>;
}
declare module 'web-ext/src/util/promisify.js' {
  declare module.exports: $Exports<'web-ext/src/util/promisify'>;
}
declare module 'web-ext/src/util/stdin.js' {
  declare module.exports: $Exports<'web-ext/src/util/stdin'>;
}
declare module 'web-ext/src/util/temp-dir.js' {
  declare module.exports: $Exports<'web-ext/src/util/temp-dir'>;
}
declare module 'web-ext/src/util/updates.js' {
  declare module.exports: $Exports<'web-ext/src/util/updates'>;
}
declare module 'web-ext/src/watcher.js' {
  declare module.exports: $Exports<'web-ext/src/watcher'>;
}
