// flow-typed signature: 540070a78db94b74a5cba16087a5d505
// flow-typed version: <<STUB>>/@nodeproto/jsync_vworkspace:0.0.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nodeproto/jsync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nodeproto/jsync' {
  declare module.exports: any;
}
