// flow-typed signature: e4d021ae8a6c8dc1e8b6f4382afdfc16
// flow-typed version: <<STUB>>/@nodeproto/configproto_vworkspace:0.0.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nodeproto/configproto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nodeproto/configproto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nodeproto/configproto/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/@babel/eslint-parser_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/@babel/eslint-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/@babel/plugin-proposal-throw-expressions_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/@babel/plugin-syntax-jsx_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/@babel/plugin-transform-flow-strip-types_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/@babel/plugin-transform-react-constant-elements_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/@babel/plugin-transform-react-inline-elements_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/@babel/plugin-transform-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/@babel/preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/@babel/preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/@babel/preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/@babel/runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/@babel/traverse_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/@octokit/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/babel-plugin-tailcall-optimization_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/babel-plugin-transform-export-default-name_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/core-js_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/eslint-plugin-html_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/eslint-plugin-json_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/eslint-plugin-markdown_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/eslint-plugin-yml_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/flow-typed/npm/yaml-eslint-parser_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/src/fixtures/auto' {
  declare module.exports: any;
}

declare module '@nodeproto/configproto/src/fixtures/react' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nodeproto/configproto/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/@babel/eslint-parser_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@babel/eslint-parser_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/@babel/eslint-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@babel/eslint-plugin_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/@babel/plugin-proposal-throw-expressions_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@babel/plugin-proposal-throw-expressions_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/@babel/plugin-syntax-jsx_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@babel/plugin-syntax-jsx_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/@babel/plugin-transform-flow-strip-types_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@babel/plugin-transform-flow-strip-types_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/@babel/plugin-transform-react-constant-elements_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@babel/plugin-transform-react-constant-elements_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/@babel/plugin-transform-react-inline-elements_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@babel/plugin-transform-react-inline-elements_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/@babel/plugin-transform-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@babel/plugin-transform-runtime_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/@babel/preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@babel/preset-env_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/@babel/preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@babel/preset-flow_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/@babel/preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@babel/preset-react_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/@babel/runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@babel/runtime_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/@babel/traverse_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@babel/traverse_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/@octokit/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/@octokit/core_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/babel-plugin-tailcall-optimization_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/babel-plugin-tailcall-optimization_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/babel-plugin-transform-export-default-name_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/babel-plugin-transform-export-default-name_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/core-js_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/core-js_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/eslint-plugin-html_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/eslint-plugin-html_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/eslint-plugin-json_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/eslint-plugin-json_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/eslint-plugin-markdown_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/eslint-plugin-markdown_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/eslint-plugin-yml_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/eslint-plugin-yml_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@nodeproto/configproto/flow-typed/npm/yaml-eslint-parser_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/flow-typed/npm/yaml-eslint-parser_vx.x.x'>;
}
declare module '@nodeproto/configproto/src/fixtures/auto.js' {
  declare module.exports: $Exports<'@nodeproto/configproto/src/fixtures/auto'>;
}
declare module '@nodeproto/configproto/src/fixtures/react.jsx' {
  declare module.exports: $Exports<'@nodeproto/configproto/src/fixtures/react'>;
}
