// flow-typed signature: 150ab7dc38d4fcf5dadde73f658c3b85
// flow-typed version: <<STUB>>/animate.css_v4.1.1/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'animate.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'animate.css' {
  declare module.exports: any;
}
