// flow-typed signature: bad24a9b140bfbb8a890794200af1cbb
// flow-typed version: <<STUB>>/animate.css_v4.1.1/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'animate.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'animate.css' {
  declare module.exports: any;
}
