// flow-typed signature: c9126572d55d6c8742d7c674596129ac
// flow-typed version: <<STUB>>/babel-preset-nodeproto_vworkspace:0.0.0/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-nodeproto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-nodeproto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-nodeproto/index' {
  declare module.exports: $Exports<'babel-preset-nodeproto'>;
}
declare module 'babel-preset-nodeproto/index.js' {
  declare module.exports: $Exports<'babel-preset-nodeproto'>;
}
