// flow-typed signature: 71e101223eae3de93a0d7b727e24b4e7
// flow-typed version: <<STUB>>/browsertime_v12.9.1/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browsertime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browsertime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browsertime/bin/browsertime' {
  declare module.exports: any;
}

declare module 'browsertime/bin/browsertimeWebPageReplay' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/browser/appConstants' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/browser/asyncAppConstants' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/browser/cpuBenchmark' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/browser/userAgent' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/browser/windowSize' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/cumulativeLayoutShift' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/cumulativeLayoutShiftInfo' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/documentHeight' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/documentSize' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/documentTitle' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/documentWidth' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/domElements' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/generator' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/largestContentfulPaintInfo' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/longTask' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/navigationStartTime' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/nextHopProtocol' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/resources' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/responsive' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/url' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/pageinfo/visualElements' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/timings/elementTimings' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/timings/firstInput' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/timings/firstPaint' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/timings/largestContentfulPaint' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/timings/loadEventEnd' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/timings/navigationTiming' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/timings/pageTimings' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/timings/paintTiming' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/timings/serverTimings' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/timings/timeToContentfulPaint' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/timings/timeToDomContentFlushed' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/timings/timeToFirstInteractive' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/timings/ttfb' {
  declare module.exports: any;
}

declare module 'browsertime/browserscripts/timings/userTimings' {
  declare module.exports: any;
}

declare module 'browsertime/lib/android/gnirehtet' {
  declare module.exports: any;
}

declare module 'browsertime/lib/android' {
  declare module.exports: any;
}

declare module 'browsertime/lib/android/root' {
  declare module.exports: any;
}

declare module 'browsertime/lib/chrome/chromeDevtoolsProtocol' {
  declare module.exports: any;
}

declare module 'browsertime/lib/chrome/har' {
  declare module.exports: any;
}

declare module 'browsertime/lib/chrome/longTaskMetrics' {
  declare module.exports: any;
}

declare module 'browsertime/lib/chrome/parseCpuTrace' {
  declare module.exports: any;
}

declare module 'browsertime/lib/chrome/settings/chromeAndroidOptions' {
  declare module.exports: any;
}

declare module 'browsertime/lib/chrome/settings/chromeDesktopOptions' {
  declare module.exports: any;
}

declare module 'browsertime/lib/chrome/settings/traceCategories' {
  declare module.exports: any;
}

declare module 'browsertime/lib/chrome/speedline' {
  declare module.exports: any;
}

declare module 'browsertime/lib/chrome/traceCategoriesParser' {
  declare module.exports: any;
}

declare module 'browsertime/lib/chrome/webdriver/builder' {
  declare module.exports: any;
}

declare module 'browsertime/lib/chrome/webdriver/chromium' {
  declare module.exports: any;
}

declare module 'browsertime/lib/chrome/webdriver/setupChromiumOptions' {
  declare module.exports: any;
}

declare module 'browsertime/lib/connectivity' {
  declare module.exports: any;
}

declare module 'browsertime/lib/connectivity/trafficShapeParser' {
  declare module.exports: any;
}

declare module 'browsertime/lib/connectivity/tsProxy' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/collector' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/addText' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/android' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/cache' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/chromeDevToolsProtocol' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/click' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/javaScript' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/measure' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/meta' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/mouse' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/navigation' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/screenshot' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/scroll' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/set' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/stopWatch' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/switch' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/util/lcpHighlightScript' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/util/lsHighlightScript' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/command/wait' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/iteration' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/engine/run' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/pageCompleteChecks/defaultPageCompleteCheck' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/pageCompleteChecks/pageCompleteCheckByInactivity' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/pageCompleteChecks/spaInactivity' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/seleniumRunner' {
  declare module.exports: any;
}

declare module 'browsertime/lib/core/webdriver' {
  declare module.exports: any;
}

declare module 'browsertime/lib/edge/webdriver/builder' {
  declare module.exports: any;
}

declare module 'browsertime/lib/extensionserver/httpServer' {
  declare module.exports: any;
}

declare module 'browsertime/lib/extensionserver' {
  declare module.exports: any;
}

declare module 'browsertime/lib/extensionserver/setup' {
  declare module.exports: any;
}

declare module 'browsertime/lib/firefox/geckoProfiler' {
  declare module.exports: any;
}

declare module 'browsertime/lib/firefox/getHAR' {
  declare module.exports: any;
}

declare module 'browsertime/lib/firefox/perfStats' {
  declare module.exports: any;
}

declare module 'browsertime/lib/firefox/settings/disableSafeBrowsingPreferences' {
  declare module.exports: any;
}

declare module 'browsertime/lib/firefox/settings/disableTrackingProtectionPreferences' {
  declare module.exports: any;
}

declare module 'browsertime/lib/firefox/settings/firefoxPreferences' {
  declare module.exports: any;
}

declare module 'browsertime/lib/firefox/settings/geckoProfilerDefaults' {
  declare module.exports: any;
}

declare module 'browsertime/lib/firefox/webdriver/builder' {
  declare module.exports: any;
}

declare module 'browsertime/lib/firefox/webdriver/firefox' {
  declare module.exports: any;
}

declare module 'browsertime/lib/safari/webdriver/builder' {
  declare module.exports: any;
}

declare module 'browsertime/lib/safari/webdriver/safari' {
  declare module.exports: any;
}

declare module 'browsertime/lib/screenshot/defaults' {
  declare module.exports: any;
}

declare module 'browsertime/lib/screenshot' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/browserScript' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/cli' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/engineUtils' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/errors' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/fileUtil' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/filters' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/getViewPort' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/har' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/images' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/logging' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/pathToFolder' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/preURL' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/setResourceTimingBufferSize' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/statistics' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/stop' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/storageManager' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/tcpdump' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/userTiming' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/util' {
  declare module.exports: any;
}

declare module 'browsertime/lib/support/xvfb' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/defaults' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/postprocessing/finetune/addTextToVideo' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/postprocessing/finetune/convertFps' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/postprocessing/finetune/getFont' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/postprocessing/finetune/getTimingMetrics' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/postprocessing/finetune' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/postprocessing/finetune/removeOrange' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/postprocessing/visualmetrics/extraMetrics' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/postprocessing/visualmetrics/getVideoMetrics' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/postprocessing/visualmetrics/visualMetrics' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/screenRecording/android/recorder' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/screenRecording/desktop/convert' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/screenRecording/desktop/desktopRecorder' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/screenRecording/desktop/ffmpegRecorder' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/screenRecording/desktop/osx/getResolution' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/screenRecording/desktop/osx/getScreen' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/screenRecording/firefox/firefoxWindowRecorder' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/screenRecording/ios/convertToMp4' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/screenRecording/ios/iosRecorder' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/screenRecording/iosSimulator/convertToMp4' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/screenRecording/iosSimulator/recorder' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/screenRecording/recorder' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/screenRecording/setOrangeBackground' {
  declare module.exports: any;
}

declare module 'browsertime/lib/video/video' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browsertime/bin/browsertime.js' {
  declare module.exports: $Exports<'browsertime/bin/browsertime'>;
}
declare module 'browsertime/bin/browsertimeWebPageReplay.js' {
  declare module.exports: $Exports<'browsertime/bin/browsertimeWebPageReplay'>;
}
declare module 'browsertime/browserscripts/browser/appConstants.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/browser/appConstants'>;
}
declare module 'browsertime/browserscripts/browser/asyncAppConstants.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/browser/asyncAppConstants'>;
}
declare module 'browsertime/browserscripts/browser/cpuBenchmark.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/browser/cpuBenchmark'>;
}
declare module 'browsertime/browserscripts/browser/userAgent.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/browser/userAgent'>;
}
declare module 'browsertime/browserscripts/browser/windowSize.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/browser/windowSize'>;
}
declare module 'browsertime/browserscripts/pageinfo/cumulativeLayoutShift.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/cumulativeLayoutShift'>;
}
declare module 'browsertime/browserscripts/pageinfo/cumulativeLayoutShiftInfo.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/cumulativeLayoutShiftInfo'>;
}
declare module 'browsertime/browserscripts/pageinfo/documentHeight.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/documentHeight'>;
}
declare module 'browsertime/browserscripts/pageinfo/documentSize.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/documentSize'>;
}
declare module 'browsertime/browserscripts/pageinfo/documentTitle.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/documentTitle'>;
}
declare module 'browsertime/browserscripts/pageinfo/documentWidth.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/documentWidth'>;
}
declare module 'browsertime/browserscripts/pageinfo/domElements.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/domElements'>;
}
declare module 'browsertime/browserscripts/pageinfo/generator.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/generator'>;
}
declare module 'browsertime/browserscripts/pageinfo/largestContentfulPaintInfo.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/largestContentfulPaintInfo'>;
}
declare module 'browsertime/browserscripts/pageinfo/longTask.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/longTask'>;
}
declare module 'browsertime/browserscripts/pageinfo/navigationStartTime.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/navigationStartTime'>;
}
declare module 'browsertime/browserscripts/pageinfo/nextHopProtocol.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/nextHopProtocol'>;
}
declare module 'browsertime/browserscripts/pageinfo/resources.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/resources'>;
}
declare module 'browsertime/browserscripts/pageinfo/responsive.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/responsive'>;
}
declare module 'browsertime/browserscripts/pageinfo/url.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/url'>;
}
declare module 'browsertime/browserscripts/pageinfo/visualElements.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/pageinfo/visualElements'>;
}
declare module 'browsertime/browserscripts/timings/elementTimings.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/timings/elementTimings'>;
}
declare module 'browsertime/browserscripts/timings/firstInput.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/timings/firstInput'>;
}
declare module 'browsertime/browserscripts/timings/firstPaint.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/timings/firstPaint'>;
}
declare module 'browsertime/browserscripts/timings/largestContentfulPaint.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/timings/largestContentfulPaint'>;
}
declare module 'browsertime/browserscripts/timings/loadEventEnd.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/timings/loadEventEnd'>;
}
declare module 'browsertime/browserscripts/timings/navigationTiming.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/timings/navigationTiming'>;
}
declare module 'browsertime/browserscripts/timings/pageTimings.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/timings/pageTimings'>;
}
declare module 'browsertime/browserscripts/timings/paintTiming.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/timings/paintTiming'>;
}
declare module 'browsertime/browserscripts/timings/serverTimings.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/timings/serverTimings'>;
}
declare module 'browsertime/browserscripts/timings/timeToContentfulPaint.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/timings/timeToContentfulPaint'>;
}
declare module 'browsertime/browserscripts/timings/timeToDomContentFlushed.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/timings/timeToDomContentFlushed'>;
}
declare module 'browsertime/browserscripts/timings/timeToFirstInteractive.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/timings/timeToFirstInteractive'>;
}
declare module 'browsertime/browserscripts/timings/ttfb.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/timings/ttfb'>;
}
declare module 'browsertime/browserscripts/timings/userTimings.js' {
  declare module.exports: $Exports<'browsertime/browserscripts/timings/userTimings'>;
}
declare module 'browsertime/index' {
  declare module.exports: $Exports<'browsertime'>;
}
declare module 'browsertime/index.js' {
  declare module.exports: $Exports<'browsertime'>;
}
declare module 'browsertime/lib/android/gnirehtet.js' {
  declare module.exports: $Exports<'browsertime/lib/android/gnirehtet'>;
}
declare module 'browsertime/lib/android/index' {
  declare module.exports: $Exports<'browsertime/lib/android'>;
}
declare module 'browsertime/lib/android/index.js' {
  declare module.exports: $Exports<'browsertime/lib/android'>;
}
declare module 'browsertime/lib/android/root.js' {
  declare module.exports: $Exports<'browsertime/lib/android/root'>;
}
declare module 'browsertime/lib/chrome/chromeDevtoolsProtocol.js' {
  declare module.exports: $Exports<'browsertime/lib/chrome/chromeDevtoolsProtocol'>;
}
declare module 'browsertime/lib/chrome/har.js' {
  declare module.exports: $Exports<'browsertime/lib/chrome/har'>;
}
declare module 'browsertime/lib/chrome/longTaskMetrics.js' {
  declare module.exports: $Exports<'browsertime/lib/chrome/longTaskMetrics'>;
}
declare module 'browsertime/lib/chrome/parseCpuTrace.js' {
  declare module.exports: $Exports<'browsertime/lib/chrome/parseCpuTrace'>;
}
declare module 'browsertime/lib/chrome/settings/chromeAndroidOptions.js' {
  declare module.exports: $Exports<'browsertime/lib/chrome/settings/chromeAndroidOptions'>;
}
declare module 'browsertime/lib/chrome/settings/chromeDesktopOptions.js' {
  declare module.exports: $Exports<'browsertime/lib/chrome/settings/chromeDesktopOptions'>;
}
declare module 'browsertime/lib/chrome/settings/traceCategories.js' {
  declare module.exports: $Exports<'browsertime/lib/chrome/settings/traceCategories'>;
}
declare module 'browsertime/lib/chrome/speedline.js' {
  declare module.exports: $Exports<'browsertime/lib/chrome/speedline'>;
}
declare module 'browsertime/lib/chrome/traceCategoriesParser.js' {
  declare module.exports: $Exports<'browsertime/lib/chrome/traceCategoriesParser'>;
}
declare module 'browsertime/lib/chrome/webdriver/builder.js' {
  declare module.exports: $Exports<'browsertime/lib/chrome/webdriver/builder'>;
}
declare module 'browsertime/lib/chrome/webdriver/chromium.js' {
  declare module.exports: $Exports<'browsertime/lib/chrome/webdriver/chromium'>;
}
declare module 'browsertime/lib/chrome/webdriver/setupChromiumOptions.js' {
  declare module.exports: $Exports<'browsertime/lib/chrome/webdriver/setupChromiumOptions'>;
}
declare module 'browsertime/lib/connectivity/index' {
  declare module.exports: $Exports<'browsertime/lib/connectivity'>;
}
declare module 'browsertime/lib/connectivity/index.js' {
  declare module.exports: $Exports<'browsertime/lib/connectivity'>;
}
declare module 'browsertime/lib/connectivity/trafficShapeParser.js' {
  declare module.exports: $Exports<'browsertime/lib/connectivity/trafficShapeParser'>;
}
declare module 'browsertime/lib/connectivity/tsProxy.js' {
  declare module.exports: $Exports<'browsertime/lib/connectivity/tsProxy'>;
}
declare module 'browsertime/lib/core/engine/collector.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/collector'>;
}
declare module 'browsertime/lib/core/engine/command/addText.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/addText'>;
}
declare module 'browsertime/lib/core/engine/command/android.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/android'>;
}
declare module 'browsertime/lib/core/engine/command/cache.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/cache'>;
}
declare module 'browsertime/lib/core/engine/command/chromeDevToolsProtocol.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/chromeDevToolsProtocol'>;
}
declare module 'browsertime/lib/core/engine/command/click.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/click'>;
}
declare module 'browsertime/lib/core/engine/command/javaScript.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/javaScript'>;
}
declare module 'browsertime/lib/core/engine/command/measure.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/measure'>;
}
declare module 'browsertime/lib/core/engine/command/meta.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/meta'>;
}
declare module 'browsertime/lib/core/engine/command/mouse.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/mouse'>;
}
declare module 'browsertime/lib/core/engine/command/navigation.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/navigation'>;
}
declare module 'browsertime/lib/core/engine/command/screenshot.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/screenshot'>;
}
declare module 'browsertime/lib/core/engine/command/scroll.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/scroll'>;
}
declare module 'browsertime/lib/core/engine/command/set.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/set'>;
}
declare module 'browsertime/lib/core/engine/command/stopWatch.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/stopWatch'>;
}
declare module 'browsertime/lib/core/engine/command/switch.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/switch'>;
}
declare module 'browsertime/lib/core/engine/command/util/lcpHighlightScript.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/util/lcpHighlightScript'>;
}
declare module 'browsertime/lib/core/engine/command/util/lsHighlightScript.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/util/lsHighlightScript'>;
}
declare module 'browsertime/lib/core/engine/command/wait.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/command/wait'>;
}
declare module 'browsertime/lib/core/engine/index' {
  declare module.exports: $Exports<'browsertime/lib/core/engine'>;
}
declare module 'browsertime/lib/core/engine/index.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine'>;
}
declare module 'browsertime/lib/core/engine/iteration.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/iteration'>;
}
declare module 'browsertime/lib/core/engine/run.js' {
  declare module.exports: $Exports<'browsertime/lib/core/engine/run'>;
}
declare module 'browsertime/lib/core/pageCompleteChecks/defaultPageCompleteCheck.js' {
  declare module.exports: $Exports<'browsertime/lib/core/pageCompleteChecks/defaultPageCompleteCheck'>;
}
declare module 'browsertime/lib/core/pageCompleteChecks/pageCompleteCheckByInactivity.js' {
  declare module.exports: $Exports<'browsertime/lib/core/pageCompleteChecks/pageCompleteCheckByInactivity'>;
}
declare module 'browsertime/lib/core/pageCompleteChecks/spaInactivity.js' {
  declare module.exports: $Exports<'browsertime/lib/core/pageCompleteChecks/spaInactivity'>;
}
declare module 'browsertime/lib/core/seleniumRunner.js' {
  declare module.exports: $Exports<'browsertime/lib/core/seleniumRunner'>;
}
declare module 'browsertime/lib/core/webdriver/index' {
  declare module.exports: $Exports<'browsertime/lib/core/webdriver'>;
}
declare module 'browsertime/lib/core/webdriver/index.js' {
  declare module.exports: $Exports<'browsertime/lib/core/webdriver'>;
}
declare module 'browsertime/lib/edge/webdriver/builder.js' {
  declare module.exports: $Exports<'browsertime/lib/edge/webdriver/builder'>;
}
declare module 'browsertime/lib/extensionserver/httpServer.js' {
  declare module.exports: $Exports<'browsertime/lib/extensionserver/httpServer'>;
}
declare module 'browsertime/lib/extensionserver/index' {
  declare module.exports: $Exports<'browsertime/lib/extensionserver'>;
}
declare module 'browsertime/lib/extensionserver/index.js' {
  declare module.exports: $Exports<'browsertime/lib/extensionserver'>;
}
declare module 'browsertime/lib/extensionserver/setup.js' {
  declare module.exports: $Exports<'browsertime/lib/extensionserver/setup'>;
}
declare module 'browsertime/lib/firefox/geckoProfiler.js' {
  declare module.exports: $Exports<'browsertime/lib/firefox/geckoProfiler'>;
}
declare module 'browsertime/lib/firefox/getHAR.js' {
  declare module.exports: $Exports<'browsertime/lib/firefox/getHAR'>;
}
declare module 'browsertime/lib/firefox/perfStats.js' {
  declare module.exports: $Exports<'browsertime/lib/firefox/perfStats'>;
}
declare module 'browsertime/lib/firefox/settings/disableSafeBrowsingPreferences.js' {
  declare module.exports: $Exports<'browsertime/lib/firefox/settings/disableSafeBrowsingPreferences'>;
}
declare module 'browsertime/lib/firefox/settings/disableTrackingProtectionPreferences.js' {
  declare module.exports: $Exports<'browsertime/lib/firefox/settings/disableTrackingProtectionPreferences'>;
}
declare module 'browsertime/lib/firefox/settings/firefoxPreferences.js' {
  declare module.exports: $Exports<'browsertime/lib/firefox/settings/firefoxPreferences'>;
}
declare module 'browsertime/lib/firefox/settings/geckoProfilerDefaults.js' {
  declare module.exports: $Exports<'browsertime/lib/firefox/settings/geckoProfilerDefaults'>;
}
declare module 'browsertime/lib/firefox/webdriver/builder.js' {
  declare module.exports: $Exports<'browsertime/lib/firefox/webdriver/builder'>;
}
declare module 'browsertime/lib/firefox/webdriver/firefox.js' {
  declare module.exports: $Exports<'browsertime/lib/firefox/webdriver/firefox'>;
}
declare module 'browsertime/lib/safari/webdriver/builder.js' {
  declare module.exports: $Exports<'browsertime/lib/safari/webdriver/builder'>;
}
declare module 'browsertime/lib/safari/webdriver/safari.js' {
  declare module.exports: $Exports<'browsertime/lib/safari/webdriver/safari'>;
}
declare module 'browsertime/lib/screenshot/defaults.js' {
  declare module.exports: $Exports<'browsertime/lib/screenshot/defaults'>;
}
declare module 'browsertime/lib/screenshot/index' {
  declare module.exports: $Exports<'browsertime/lib/screenshot'>;
}
declare module 'browsertime/lib/screenshot/index.js' {
  declare module.exports: $Exports<'browsertime/lib/screenshot'>;
}
declare module 'browsertime/lib/support/browserScript.js' {
  declare module.exports: $Exports<'browsertime/lib/support/browserScript'>;
}
declare module 'browsertime/lib/support/cli.js' {
  declare module.exports: $Exports<'browsertime/lib/support/cli'>;
}
declare module 'browsertime/lib/support/engineUtils.js' {
  declare module.exports: $Exports<'browsertime/lib/support/engineUtils'>;
}
declare module 'browsertime/lib/support/errors.js' {
  declare module.exports: $Exports<'browsertime/lib/support/errors'>;
}
declare module 'browsertime/lib/support/fileUtil.js' {
  declare module.exports: $Exports<'browsertime/lib/support/fileUtil'>;
}
declare module 'browsertime/lib/support/filters.js' {
  declare module.exports: $Exports<'browsertime/lib/support/filters'>;
}
declare module 'browsertime/lib/support/getViewPort.js' {
  declare module.exports: $Exports<'browsertime/lib/support/getViewPort'>;
}
declare module 'browsertime/lib/support/har/index' {
  declare module.exports: $Exports<'browsertime/lib/support/har'>;
}
declare module 'browsertime/lib/support/har/index.js' {
  declare module.exports: $Exports<'browsertime/lib/support/har'>;
}
declare module 'browsertime/lib/support/images/index' {
  declare module.exports: $Exports<'browsertime/lib/support/images'>;
}
declare module 'browsertime/lib/support/images/index.js' {
  declare module.exports: $Exports<'browsertime/lib/support/images'>;
}
declare module 'browsertime/lib/support/logging.js' {
  declare module.exports: $Exports<'browsertime/lib/support/logging'>;
}
declare module 'browsertime/lib/support/pathToFolder.js' {
  declare module.exports: $Exports<'browsertime/lib/support/pathToFolder'>;
}
declare module 'browsertime/lib/support/preURL.js' {
  declare module.exports: $Exports<'browsertime/lib/support/preURL'>;
}
declare module 'browsertime/lib/support/setResourceTimingBufferSize.js' {
  declare module.exports: $Exports<'browsertime/lib/support/setResourceTimingBufferSize'>;
}
declare module 'browsertime/lib/support/statistics.js' {
  declare module.exports: $Exports<'browsertime/lib/support/statistics'>;
}
declare module 'browsertime/lib/support/stop.js' {
  declare module.exports: $Exports<'browsertime/lib/support/stop'>;
}
declare module 'browsertime/lib/support/storageManager.js' {
  declare module.exports: $Exports<'browsertime/lib/support/storageManager'>;
}
declare module 'browsertime/lib/support/tcpdump.js' {
  declare module.exports: $Exports<'browsertime/lib/support/tcpdump'>;
}
declare module 'browsertime/lib/support/userTiming.js' {
  declare module.exports: $Exports<'browsertime/lib/support/userTiming'>;
}
declare module 'browsertime/lib/support/util.js' {
  declare module.exports: $Exports<'browsertime/lib/support/util'>;
}
declare module 'browsertime/lib/support/xvfb.js' {
  declare module.exports: $Exports<'browsertime/lib/support/xvfb'>;
}
declare module 'browsertime/lib/video/defaults.js' {
  declare module.exports: $Exports<'browsertime/lib/video/defaults'>;
}
declare module 'browsertime/lib/video/postprocessing/finetune/addTextToVideo.js' {
  declare module.exports: $Exports<'browsertime/lib/video/postprocessing/finetune/addTextToVideo'>;
}
declare module 'browsertime/lib/video/postprocessing/finetune/convertFps.js' {
  declare module.exports: $Exports<'browsertime/lib/video/postprocessing/finetune/convertFps'>;
}
declare module 'browsertime/lib/video/postprocessing/finetune/getFont.js' {
  declare module.exports: $Exports<'browsertime/lib/video/postprocessing/finetune/getFont'>;
}
declare module 'browsertime/lib/video/postprocessing/finetune/getTimingMetrics.js' {
  declare module.exports: $Exports<'browsertime/lib/video/postprocessing/finetune/getTimingMetrics'>;
}
declare module 'browsertime/lib/video/postprocessing/finetune/index' {
  declare module.exports: $Exports<'browsertime/lib/video/postprocessing/finetune'>;
}
declare module 'browsertime/lib/video/postprocessing/finetune/index.js' {
  declare module.exports: $Exports<'browsertime/lib/video/postprocessing/finetune'>;
}
declare module 'browsertime/lib/video/postprocessing/finetune/removeOrange.js' {
  declare module.exports: $Exports<'browsertime/lib/video/postprocessing/finetune/removeOrange'>;
}
declare module 'browsertime/lib/video/postprocessing/visualmetrics/extraMetrics.js' {
  declare module.exports: $Exports<'browsertime/lib/video/postprocessing/visualmetrics/extraMetrics'>;
}
declare module 'browsertime/lib/video/postprocessing/visualmetrics/getVideoMetrics.js' {
  declare module.exports: $Exports<'browsertime/lib/video/postprocessing/visualmetrics/getVideoMetrics'>;
}
declare module 'browsertime/lib/video/postprocessing/visualmetrics/visualMetrics.js' {
  declare module.exports: $Exports<'browsertime/lib/video/postprocessing/visualmetrics/visualMetrics'>;
}
declare module 'browsertime/lib/video/screenRecording/android/recorder.js' {
  declare module.exports: $Exports<'browsertime/lib/video/screenRecording/android/recorder'>;
}
declare module 'browsertime/lib/video/screenRecording/desktop/convert.js' {
  declare module.exports: $Exports<'browsertime/lib/video/screenRecording/desktop/convert'>;
}
declare module 'browsertime/lib/video/screenRecording/desktop/desktopRecorder.js' {
  declare module.exports: $Exports<'browsertime/lib/video/screenRecording/desktop/desktopRecorder'>;
}
declare module 'browsertime/lib/video/screenRecording/desktop/ffmpegRecorder.js' {
  declare module.exports: $Exports<'browsertime/lib/video/screenRecording/desktop/ffmpegRecorder'>;
}
declare module 'browsertime/lib/video/screenRecording/desktop/osx/getResolution.js' {
  declare module.exports: $Exports<'browsertime/lib/video/screenRecording/desktop/osx/getResolution'>;
}
declare module 'browsertime/lib/video/screenRecording/desktop/osx/getScreen.js' {
  declare module.exports: $Exports<'browsertime/lib/video/screenRecording/desktop/osx/getScreen'>;
}
declare module 'browsertime/lib/video/screenRecording/firefox/firefoxWindowRecorder.js' {
  declare module.exports: $Exports<'browsertime/lib/video/screenRecording/firefox/firefoxWindowRecorder'>;
}
declare module 'browsertime/lib/video/screenRecording/ios/convertToMp4.js' {
  declare module.exports: $Exports<'browsertime/lib/video/screenRecording/ios/convertToMp4'>;
}
declare module 'browsertime/lib/video/screenRecording/ios/iosRecorder.js' {
  declare module.exports: $Exports<'browsertime/lib/video/screenRecording/ios/iosRecorder'>;
}
declare module 'browsertime/lib/video/screenRecording/iosSimulator/convertToMp4.js' {
  declare module.exports: $Exports<'browsertime/lib/video/screenRecording/iosSimulator/convertToMp4'>;
}
declare module 'browsertime/lib/video/screenRecording/iosSimulator/recorder.js' {
  declare module.exports: $Exports<'browsertime/lib/video/screenRecording/iosSimulator/recorder'>;
}
declare module 'browsertime/lib/video/screenRecording/recorder.js' {
  declare module.exports: $Exports<'browsertime/lib/video/screenRecording/recorder'>;
}
declare module 'browsertime/lib/video/screenRecording/setOrangeBackground.js' {
  declare module.exports: $Exports<'browsertime/lib/video/screenRecording/setOrangeBackground'>;
}
declare module 'browsertime/lib/video/video.js' {
  declare module.exports: $Exports<'browsertime/lib/video/video'>;
}
