// flow-typed signature: 4b877bed2098703a058eba31a77b0464
// flow-typed version: <<STUB>>/concurrently_v6.2.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'concurrently'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'concurrently' {
  declare module.exports: any;
}
