// flow-typed signature: bec70248591c273a330e13a0b6409e8d
// flow-typed version: <<STUB>>/concurrently_v7.1.0/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'concurrently'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'concurrently' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'concurrently/dist/bin/concurrently' {
  declare module.exports: any;
}

declare module 'concurrently/dist/bin/epilogue' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/command-parser/command-parser' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/command-parser/expand-npm-shortcut' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/command-parser/expand-npm-wildcard' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/command-parser/strip-quotes' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/command' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/completion-listener' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/concurrently' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/defaults' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/flow-control/flow-controller' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/flow-control/input-handler' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/flow-control/kill-on-signal' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/flow-control/kill-others' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/flow-control/log-error' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/flow-control/log-exit' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/flow-control/log-output' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/flow-control/log-timings' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/flow-control/restart-process' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/get-spawn-opts' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/logger' {
  declare module.exports: any;
}

declare module 'concurrently/dist/src/output-writer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'concurrently/dist/bin/concurrently.js' {
  declare module.exports: $Exports<'concurrently/dist/bin/concurrently'>;
}
declare module 'concurrently/dist/bin/epilogue.js' {
  declare module.exports: $Exports<'concurrently/dist/bin/epilogue'>;
}
declare module 'concurrently/dist/src/command-parser/command-parser.js' {
  declare module.exports: $Exports<'concurrently/dist/src/command-parser/command-parser'>;
}
declare module 'concurrently/dist/src/command-parser/expand-npm-shortcut.js' {
  declare module.exports: $Exports<'concurrently/dist/src/command-parser/expand-npm-shortcut'>;
}
declare module 'concurrently/dist/src/command-parser/expand-npm-wildcard.js' {
  declare module.exports: $Exports<'concurrently/dist/src/command-parser/expand-npm-wildcard'>;
}
declare module 'concurrently/dist/src/command-parser/strip-quotes.js' {
  declare module.exports: $Exports<'concurrently/dist/src/command-parser/strip-quotes'>;
}
declare module 'concurrently/dist/src/command.js' {
  declare module.exports: $Exports<'concurrently/dist/src/command'>;
}
declare module 'concurrently/dist/src/completion-listener.js' {
  declare module.exports: $Exports<'concurrently/dist/src/completion-listener'>;
}
declare module 'concurrently/dist/src/concurrently.js' {
  declare module.exports: $Exports<'concurrently/dist/src/concurrently'>;
}
declare module 'concurrently/dist/src/defaults.js' {
  declare module.exports: $Exports<'concurrently/dist/src/defaults'>;
}
declare module 'concurrently/dist/src/flow-control/flow-controller.js' {
  declare module.exports: $Exports<'concurrently/dist/src/flow-control/flow-controller'>;
}
declare module 'concurrently/dist/src/flow-control/input-handler.js' {
  declare module.exports: $Exports<'concurrently/dist/src/flow-control/input-handler'>;
}
declare module 'concurrently/dist/src/flow-control/kill-on-signal.js' {
  declare module.exports: $Exports<'concurrently/dist/src/flow-control/kill-on-signal'>;
}
declare module 'concurrently/dist/src/flow-control/kill-others.js' {
  declare module.exports: $Exports<'concurrently/dist/src/flow-control/kill-others'>;
}
declare module 'concurrently/dist/src/flow-control/log-error.js' {
  declare module.exports: $Exports<'concurrently/dist/src/flow-control/log-error'>;
}
declare module 'concurrently/dist/src/flow-control/log-exit.js' {
  declare module.exports: $Exports<'concurrently/dist/src/flow-control/log-exit'>;
}
declare module 'concurrently/dist/src/flow-control/log-output.js' {
  declare module.exports: $Exports<'concurrently/dist/src/flow-control/log-output'>;
}
declare module 'concurrently/dist/src/flow-control/log-timings.js' {
  declare module.exports: $Exports<'concurrently/dist/src/flow-control/log-timings'>;
}
declare module 'concurrently/dist/src/flow-control/restart-process.js' {
  declare module.exports: $Exports<'concurrently/dist/src/flow-control/restart-process'>;
}
declare module 'concurrently/dist/src/get-spawn-opts.js' {
  declare module.exports: $Exports<'concurrently/dist/src/get-spawn-opts'>;
}
declare module 'concurrently/dist/src/index' {
  declare module.exports: $Exports<'concurrently/dist/src'>;
}
declare module 'concurrently/dist/src/index.js' {
  declare module.exports: $Exports<'concurrently/dist/src'>;
}
declare module 'concurrently/dist/src/logger.js' {
  declare module.exports: $Exports<'concurrently/dist/src/logger'>;
}
declare module 'concurrently/dist/src/output-writer.js' {
  declare module.exports: $Exports<'concurrently/dist/src/output-writer'>;
}
declare module 'concurrently/index' {
  declare module.exports: $Exports<'concurrently'>;
}
declare module 'concurrently/index.js' {
  declare module.exports: $Exports<'concurrently'>;
}
