// flow-typed signature: 92fd542abdae8955e635016d53789731
// flow-typed version: <<STUB>>/env-cmd_v10.1.0/flow_v0.170.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'env-cmd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'env-cmd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'env-cmd/bin/env-cmd' {
  declare module.exports: any;
}

declare module 'env-cmd/dist/env-cmd' {
  declare module.exports: any;
}

declare module 'env-cmd/dist/expand-envs' {
  declare module.exports: any;
}

declare module 'env-cmd/dist/get-env-vars' {
  declare module.exports: any;
}

declare module 'env-cmd/dist' {
  declare module.exports: any;
}

declare module 'env-cmd/dist/parse-args' {
  declare module.exports: any;
}

declare module 'env-cmd/dist/parse-env-file' {
  declare module.exports: any;
}

declare module 'env-cmd/dist/parse-rc-file' {
  declare module.exports: any;
}

declare module 'env-cmd/dist/signal-termination' {
  declare module.exports: any;
}

declare module 'env-cmd/dist/spawn' {
  declare module.exports: any;
}

declare module 'env-cmd/dist/types' {
  declare module.exports: any;
}

declare module 'env-cmd/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'env-cmd/bin/env-cmd.js' {
  declare module.exports: $Exports<'env-cmd/bin/env-cmd'>;
}
declare module 'env-cmd/dist/env-cmd.js' {
  declare module.exports: $Exports<'env-cmd/dist/env-cmd'>;
}
declare module 'env-cmd/dist/expand-envs.js' {
  declare module.exports: $Exports<'env-cmd/dist/expand-envs'>;
}
declare module 'env-cmd/dist/get-env-vars.js' {
  declare module.exports: $Exports<'env-cmd/dist/get-env-vars'>;
}
declare module 'env-cmd/dist/index' {
  declare module.exports: $Exports<'env-cmd/dist'>;
}
declare module 'env-cmd/dist/index.js' {
  declare module.exports: $Exports<'env-cmd/dist'>;
}
declare module 'env-cmd/dist/parse-args.js' {
  declare module.exports: $Exports<'env-cmd/dist/parse-args'>;
}
declare module 'env-cmd/dist/parse-env-file.js' {
  declare module.exports: $Exports<'env-cmd/dist/parse-env-file'>;
}
declare module 'env-cmd/dist/parse-rc-file.js' {
  declare module.exports: $Exports<'env-cmd/dist/parse-rc-file'>;
}
declare module 'env-cmd/dist/signal-termination.js' {
  declare module.exports: $Exports<'env-cmd/dist/signal-termination'>;
}
declare module 'env-cmd/dist/spawn.js' {
  declare module.exports: $Exports<'env-cmd/dist/spawn'>;
}
declare module 'env-cmd/dist/types.js' {
  declare module.exports: $Exports<'env-cmd/dist/types'>;
}
declare module 'env-cmd/dist/utils.js' {
  declare module.exports: $Exports<'env-cmd/dist/utils'>;
}
