// flow-typed signature: 9ce2d3eadca731ee81a822fc47c1e03f
// flow-typed version: <<STUB>>/hint_v6.1.4/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hint' {
  declare module.exports: any;
}
