// flow-typed signature: bbfaaaacd8f683e735a0148e2ae35d54
// flow-typed version: <<STUB>>/milligram_v1.4.1/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'milligram'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'milligram' {
  declare module.exports: any;
}
