// flow-typed signature: f010fafd531112d6fa7c614e19a7c6d6
// flow-typed version: <<STUB>>/modernizr_v3.11.7/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'modernizr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'modernizr' {
  declare module.exports: any;
}
