// flow-typed signature: d0c0c6bfa0f8b5920b1a64c85bfbf0a5
// flow-typed version: <<STUB>>/multi-tape_v1.6.1/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multi-tape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'multi-tape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'multi-tape/build' {
  declare module.exports: any;
}

declare module 'multi-tape/build/lib/glob' {
  declare module.exports: any;
}

declare module 'multi-tape/build/lib/run-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'multi-tape/build/index' {
  declare module.exports: $Exports<'multi-tape/build'>;
}
declare module 'multi-tape/build/index.js' {
  declare module.exports: $Exports<'multi-tape/build'>;
}
declare module 'multi-tape/build/lib/glob.js' {
  declare module.exports: $Exports<'multi-tape/build/lib/glob'>;
}
declare module 'multi-tape/build/lib/run-test.js' {
  declare module.exports: $Exports<'multi-tape/build/lib/run-test'>;
}
