// flow-typed signature: dd64a75f98e91f88b5efd97edf300000
// flow-typed version: <<STUB>>/normalize.css_v8.0.1/flow_v0.170.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
