// flow-typed signature: eeba1d085a94c501bcec8247d3efe21e
// flow-typed version: <<STUB>>/react-icons_v4.2.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-icons' {
  declare module.exports: any;
}
