// flow-typed signature: 1610aab5139528db01a513585ae4a298
// flow-typed version: <<STUB>>/react-aria_v3.10.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-aria'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-aria' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-aria/dist/main' {
  declare module.exports: any;
}

declare module 'react-aria/dist/module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-aria/dist/main.js' {
  declare module.exports: $Exports<'react-aria/dist/main'>;
}
declare module 'react-aria/dist/module.js' {
  declare module.exports: $Exports<'react-aria/dist/module'>;
}
