// flow-typed signature: 4016287ee026dc59067a77e8f95d6451
// flow-typed version: <<STUB>>/react-json-pretty_v2.2.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-json-pretty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-json-pretty' {
  declare module.exports: any;
}
