// flow-typed signature: 4e04c847c9ca34e149274ec9286bddbe
// flow-typed version: <<STUB>>/react-aria_v3.8.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-aria'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-aria' {
  declare module.exports: any;
}
