// flow-typed signature: 4ecdbb9ea94ac4895f9a21e67b6d3fe7
// flow-typed version: <<STUB>>/react-stately_v3.9.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-stately'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-stately' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-stately/dist/main' {
  declare module.exports: any;
}

declare module 'react-stately/dist/module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-stately/dist/main.js' {
  declare module.exports: $Exports<'react-stately/dist/main'>;
}
declare module 'react-stately/dist/module.js' {
  declare module.exports: $Exports<'react-stately/dist/module'>;
}
