// flow-typed signature: bb19489cd164134d2eada833a25d0ad2
// flow-typed version: <<STUB>>/react-stately_v3.7.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-stately'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-stately' {
  declare module.exports: any;
}
