// flow-typed signature: 31b4147106d003d4053eb4c3de829c2d
// flow-typed version: <<STUB>>/react-json-pretty_v2.2.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-json-pretty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-json-pretty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-json-pretty/dist/1337' {
  declare module.exports: any;
}

declare module 'react-json-pretty/dist/acai' {
  declare module.exports: any;
}

declare module 'react-json-pretty/dist/adventure_time' {
  declare module.exports: any;
}

declare module 'react-json-pretty/dist/JSONPretty' {
  declare module.exports: any;
}

declare module 'react-json-pretty/dist/monikai' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-json-pretty/dist/1337.js' {
  declare module.exports: $Exports<'react-json-pretty/dist/1337'>;
}
declare module 'react-json-pretty/dist/acai.js' {
  declare module.exports: $Exports<'react-json-pretty/dist/acai'>;
}
declare module 'react-json-pretty/dist/adventure_time.js' {
  declare module.exports: $Exports<'react-json-pretty/dist/adventure_time'>;
}
declare module 'react-json-pretty/dist/JSONPretty.js' {
  declare module.exports: $Exports<'react-json-pretty/dist/JSONPretty'>;
}
declare module 'react-json-pretty/dist/monikai.js' {
  declare module.exports: $Exports<'react-json-pretty/dist/monikai'>;
}
