// flow-typed signature: 6328b02218ad0e801779713a0e06deab
// flow-typed version: <<STUB>>/reakit_v1.3.8/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reakit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reakit' {
  declare module.exports: any;
}
