// flow-typed signature: 5cf89b518de2df76bac949166148f795
// flow-typed version: <<STUB>>/webpack-dev-middleware-2_v5.0.2/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-middleware-2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-middleware-2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-dev-middleware-2/dist/bffs' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware-2/dist/bffs/useKoa2' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware-2/dist/cjs' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware-2/dist' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware-2/dist/middleware' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware-2/dist/utils/getFilenameFromUrl' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware-2/dist/utils/getPaths' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware-2/dist/utils/handleRangeHeaders' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware-2/dist/utils/ready' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware-2/dist/utils/setupHooks' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware-2/dist/utils/setupOutputFileSystem' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware-2/dist/utils/setupWriteToDisk' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-dev-middleware-2/dist/bffs/index' {
  declare module.exports: $Exports<'webpack-dev-middleware-2/dist/bffs'>;
}
declare module 'webpack-dev-middleware-2/dist/bffs/index.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-2/dist/bffs'>;
}
declare module 'webpack-dev-middleware-2/dist/bffs/useKoa2.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-2/dist/bffs/useKoa2'>;
}
declare module 'webpack-dev-middleware-2/dist/cjs.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-2/dist/cjs'>;
}
declare module 'webpack-dev-middleware-2/dist/index' {
  declare module.exports: $Exports<'webpack-dev-middleware-2/dist'>;
}
declare module 'webpack-dev-middleware-2/dist/index.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-2/dist'>;
}
declare module 'webpack-dev-middleware-2/dist/middleware.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-2/dist/middleware'>;
}
declare module 'webpack-dev-middleware-2/dist/utils/getFilenameFromUrl.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-2/dist/utils/getFilenameFromUrl'>;
}
declare module 'webpack-dev-middleware-2/dist/utils/getPaths.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-2/dist/utils/getPaths'>;
}
declare module 'webpack-dev-middleware-2/dist/utils/handleRangeHeaders.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-2/dist/utils/handleRangeHeaders'>;
}
declare module 'webpack-dev-middleware-2/dist/utils/ready.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-2/dist/utils/ready'>;
}
declare module 'webpack-dev-middleware-2/dist/utils/setupHooks.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-2/dist/utils/setupHooks'>;
}
declare module 'webpack-dev-middleware-2/dist/utils/setupOutputFileSystem.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-2/dist/utils/setupOutputFileSystem'>;
}
declare module 'webpack-dev-middleware-2/dist/utils/setupWriteToDisk.js' {
  declare module.exports: $Exports<'webpack-dev-middleware-2/dist/utils/setupWriteToDisk'>;
}
