// flow-typed signature: f130361be05d16ec9f3e629bd3b4e054
// flow-typed version: <<STUB>>/@babel/eslint-parser_v7.14.5/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
