// flow-typed signature: 3453b7a2f7604035724f274bccdaa50a
// flow-typed version: <<STUB>>/@babel/preset-modules_v0.1.4/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/preset-modules/lib' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/lib/plugins/transform-async-arrows-in-class' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/lib/plugins/transform-edge-default-parameters' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/lib/plugins/transform-edge-function-name' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/lib/plugins/transform-jsx-spread' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/lib/plugins/transform-safari-block-shadowing' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/lib/plugins/transform-safari-for-shadowing' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/lib/plugins/transform-tagged-template-caching' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/src' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/src/plugins/transform-async-arrows-in-class' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/src/plugins/transform-edge-default-parameters' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/src/plugins/transform-edge-function-name' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/src/plugins/transform-jsx-spread' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/src/plugins/transform-safari-block-shadowing' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/src/plugins/transform-safari-for-shadowing' {
  declare module.exports: any;
}

declare module '@babel/preset-modules/src/plugins/transform-tagged-template-caching' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/preset-modules/lib/index' {
  declare module.exports: $Exports<'@babel/preset-modules/lib'>;
}
declare module '@babel/preset-modules/lib/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/lib'>;
}
declare module '@babel/preset-modules/lib/plugins/transform-async-arrows-in-class/index' {
  declare module.exports: $Exports<'@babel/preset-modules/lib/plugins/transform-async-arrows-in-class'>;
}
declare module '@babel/preset-modules/lib/plugins/transform-async-arrows-in-class/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/lib/plugins/transform-async-arrows-in-class'>;
}
declare module '@babel/preset-modules/lib/plugins/transform-edge-default-parameters/index' {
  declare module.exports: $Exports<'@babel/preset-modules/lib/plugins/transform-edge-default-parameters'>;
}
declare module '@babel/preset-modules/lib/plugins/transform-edge-default-parameters/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/lib/plugins/transform-edge-default-parameters'>;
}
declare module '@babel/preset-modules/lib/plugins/transform-edge-function-name/index' {
  declare module.exports: $Exports<'@babel/preset-modules/lib/plugins/transform-edge-function-name'>;
}
declare module '@babel/preset-modules/lib/plugins/transform-edge-function-name/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/lib/plugins/transform-edge-function-name'>;
}
declare module '@babel/preset-modules/lib/plugins/transform-jsx-spread/index' {
  declare module.exports: $Exports<'@babel/preset-modules/lib/plugins/transform-jsx-spread'>;
}
declare module '@babel/preset-modules/lib/plugins/transform-jsx-spread/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/lib/plugins/transform-jsx-spread'>;
}
declare module '@babel/preset-modules/lib/plugins/transform-safari-block-shadowing/index' {
  declare module.exports: $Exports<'@babel/preset-modules/lib/plugins/transform-safari-block-shadowing'>;
}
declare module '@babel/preset-modules/lib/plugins/transform-safari-block-shadowing/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/lib/plugins/transform-safari-block-shadowing'>;
}
declare module '@babel/preset-modules/lib/plugins/transform-safari-for-shadowing/index' {
  declare module.exports: $Exports<'@babel/preset-modules/lib/plugins/transform-safari-for-shadowing'>;
}
declare module '@babel/preset-modules/lib/plugins/transform-safari-for-shadowing/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/lib/plugins/transform-safari-for-shadowing'>;
}
declare module '@babel/preset-modules/lib/plugins/transform-tagged-template-caching/index' {
  declare module.exports: $Exports<'@babel/preset-modules/lib/plugins/transform-tagged-template-caching'>;
}
declare module '@babel/preset-modules/lib/plugins/transform-tagged-template-caching/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/lib/plugins/transform-tagged-template-caching'>;
}
declare module '@babel/preset-modules/src/index' {
  declare module.exports: $Exports<'@babel/preset-modules/src'>;
}
declare module '@babel/preset-modules/src/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/src'>;
}
declare module '@babel/preset-modules/src/plugins/transform-async-arrows-in-class/index' {
  declare module.exports: $Exports<'@babel/preset-modules/src/plugins/transform-async-arrows-in-class'>;
}
declare module '@babel/preset-modules/src/plugins/transform-async-arrows-in-class/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/src/plugins/transform-async-arrows-in-class'>;
}
declare module '@babel/preset-modules/src/plugins/transform-edge-default-parameters/index' {
  declare module.exports: $Exports<'@babel/preset-modules/src/plugins/transform-edge-default-parameters'>;
}
declare module '@babel/preset-modules/src/plugins/transform-edge-default-parameters/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/src/plugins/transform-edge-default-parameters'>;
}
declare module '@babel/preset-modules/src/plugins/transform-edge-function-name/index' {
  declare module.exports: $Exports<'@babel/preset-modules/src/plugins/transform-edge-function-name'>;
}
declare module '@babel/preset-modules/src/plugins/transform-edge-function-name/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/src/plugins/transform-edge-function-name'>;
}
declare module '@babel/preset-modules/src/plugins/transform-jsx-spread/index' {
  declare module.exports: $Exports<'@babel/preset-modules/src/plugins/transform-jsx-spread'>;
}
declare module '@babel/preset-modules/src/plugins/transform-jsx-spread/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/src/plugins/transform-jsx-spread'>;
}
declare module '@babel/preset-modules/src/plugins/transform-safari-block-shadowing/index' {
  declare module.exports: $Exports<'@babel/preset-modules/src/plugins/transform-safari-block-shadowing'>;
}
declare module '@babel/preset-modules/src/plugins/transform-safari-block-shadowing/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/src/plugins/transform-safari-block-shadowing'>;
}
declare module '@babel/preset-modules/src/plugins/transform-safari-for-shadowing/index' {
  declare module.exports: $Exports<'@babel/preset-modules/src/plugins/transform-safari-for-shadowing'>;
}
declare module '@babel/preset-modules/src/plugins/transform-safari-for-shadowing/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/src/plugins/transform-safari-for-shadowing'>;
}
declare module '@babel/preset-modules/src/plugins/transform-tagged-template-caching/index' {
  declare module.exports: $Exports<'@babel/preset-modules/src/plugins/transform-tagged-template-caching'>;
}
declare module '@babel/preset-modules/src/plugins/transform-tagged-template-caching/index.js' {
  declare module.exports: $Exports<'@babel/preset-modules/src/plugins/transform-tagged-template-caching'>;
}
