// flow-typed signature: 0b32850f0e57e071fdd80d0ad93f0a21
// flow-typed version: <<STUB>>/@reach/router_vgithub:noahehall/router/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reach/router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reach/router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@reach/router/build/babel-preset' {
  declare module.exports: any;
}

declare module '@reach/router/build/build' {
  declare module.exports: any;
}

declare module '@reach/router/es' {
  declare module.exports: any;
}

declare module '@reach/router/es/lib/history' {
  declare module.exports: any;
}

declare module '@reach/router/es/lib/utils' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/config/env' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/config/jest/cssTransform' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/config/jest/fileTransform' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/config/paths' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/config/polyfills' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/config/webpack.config.dev' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/config/webpack.config.prod' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/config/webpackDevServer.config' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/scripts/build' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/scripts/start' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/scripts/test' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/src/App' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/src' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/src/utils' {
  declare module.exports: any;
}

declare module '@reach/router/examples/crud/src/withCache' {
  declare module.exports: any;
}

declare module '@reach/router/lib/history' {
  declare module.exports: any;
}

declare module '@reach/router/lib/utils' {
  declare module.exports: any;
}

declare module '@reach/router/rollup.config' {
  declare module.exports: any;
}

declare module '@reach/router/scripts/test' {
  declare module.exports: any;
}

declare module '@reach/router/src' {
  declare module.exports: any;
}

declare module '@reach/router/src/index.test' {
  declare module.exports: any;
}

declare module '@reach/router/src/lib/history' {
  declare module.exports: any;
}

declare module '@reach/router/src/lib/history.test' {
  declare module.exports: any;
}

declare module '@reach/router/src/lib/utils' {
  declare module.exports: any;
}

declare module '@reach/router/src/lib/utils.test' {
  declare module.exports: any;
}

declare module '@reach/router/umd/reach-router' {
  declare module.exports: any;
}

declare module '@reach/router/umd/reach-router.min' {
  declare module.exports: any;
}

declare module '@reach/router/website/build/markdown-loader' {
  declare module.exports: any;
}

declare module '@reach/router/website/src/App' {
  declare module.exports: any;
}

declare module '@reach/router/website/src' {
  declare module.exports: any;
}

declare module '@reach/router/website/src/Logo' {
  declare module.exports: any;
}

declare module '@reach/router/website/src/Nav' {
  declare module.exports: any;
}

declare module '@reach/router/website/src/polyfills' {
  declare module.exports: any;
}

declare module '@reach/router/website/src/theme' {
  declare module.exports: any;
}

declare module '@reach/router/website/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@reach/router/build/babel-preset.js' {
  declare module.exports: $Exports<'@reach/router/build/babel-preset'>;
}
declare module '@reach/router/build/build.js' {
  declare module.exports: $Exports<'@reach/router/build/build'>;
}
declare module '@reach/router/es/index' {
  declare module.exports: $Exports<'@reach/router/es'>;
}
declare module '@reach/router/es/index.js' {
  declare module.exports: $Exports<'@reach/router/es'>;
}
declare module '@reach/router/es/lib/history.js' {
  declare module.exports: $Exports<'@reach/router/es/lib/history'>;
}
declare module '@reach/router/es/lib/utils.js' {
  declare module.exports: $Exports<'@reach/router/es/lib/utils'>;
}
declare module '@reach/router/examples/crud/config/env.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/config/env'>;
}
declare module '@reach/router/examples/crud/config/jest/cssTransform.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/config/jest/cssTransform'>;
}
declare module '@reach/router/examples/crud/config/jest/fileTransform.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/config/jest/fileTransform'>;
}
declare module '@reach/router/examples/crud/config/paths.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/config/paths'>;
}
declare module '@reach/router/examples/crud/config/polyfills.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/config/polyfills'>;
}
declare module '@reach/router/examples/crud/config/webpack.config.dev.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/config/webpack.config.dev'>;
}
declare module '@reach/router/examples/crud/config/webpack.config.prod.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/config/webpack.config.prod'>;
}
declare module '@reach/router/examples/crud/config/webpackDevServer.config.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/config/webpackDevServer.config'>;
}
declare module '@reach/router/examples/crud/scripts/build.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/scripts/build'>;
}
declare module '@reach/router/examples/crud/scripts/start.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/scripts/start'>;
}
declare module '@reach/router/examples/crud/scripts/test.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/scripts/test'>;
}
declare module '@reach/router/examples/crud/src/App.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/src/App'>;
}
declare module '@reach/router/examples/crud/src/index' {
  declare module.exports: $Exports<'@reach/router/examples/crud/src'>;
}
declare module '@reach/router/examples/crud/src/index.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/src'>;
}
declare module '@reach/router/examples/crud/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/src/registerServiceWorker'>;
}
declare module '@reach/router/examples/crud/src/utils.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/src/utils'>;
}
declare module '@reach/router/examples/crud/src/withCache.js' {
  declare module.exports: $Exports<'@reach/router/examples/crud/src/withCache'>;
}
declare module '@reach/router/index' {
  declare module.exports: $Exports<'@reach/router'>;
}
declare module '@reach/router/index.js' {
  declare module.exports: $Exports<'@reach/router'>;
}
declare module '@reach/router/lib/history.js' {
  declare module.exports: $Exports<'@reach/router/lib/history'>;
}
declare module '@reach/router/lib/utils.js' {
  declare module.exports: $Exports<'@reach/router/lib/utils'>;
}
declare module '@reach/router/rollup.config.js' {
  declare module.exports: $Exports<'@reach/router/rollup.config'>;
}
declare module '@reach/router/scripts/test.js' {
  declare module.exports: $Exports<'@reach/router/scripts/test'>;
}
declare module '@reach/router/src/index' {
  declare module.exports: $Exports<'@reach/router/src'>;
}
declare module '@reach/router/src/index.js' {
  declare module.exports: $Exports<'@reach/router/src'>;
}
declare module '@reach/router/src/index.test.js' {
  declare module.exports: $Exports<'@reach/router/src/index.test'>;
}
declare module '@reach/router/src/lib/history.js' {
  declare module.exports: $Exports<'@reach/router/src/lib/history'>;
}
declare module '@reach/router/src/lib/history.test.js' {
  declare module.exports: $Exports<'@reach/router/src/lib/history.test'>;
}
declare module '@reach/router/src/lib/utils.js' {
  declare module.exports: $Exports<'@reach/router/src/lib/utils'>;
}
declare module '@reach/router/src/lib/utils.test.js' {
  declare module.exports: $Exports<'@reach/router/src/lib/utils.test'>;
}
declare module '@reach/router/umd/reach-router.js' {
  declare module.exports: $Exports<'@reach/router/umd/reach-router'>;
}
declare module '@reach/router/umd/reach-router.min.js' {
  declare module.exports: $Exports<'@reach/router/umd/reach-router.min'>;
}
declare module '@reach/router/website/build/markdown-loader.js' {
  declare module.exports: $Exports<'@reach/router/website/build/markdown-loader'>;
}
declare module '@reach/router/website/src/App.js' {
  declare module.exports: $Exports<'@reach/router/website/src/App'>;
}
declare module '@reach/router/website/src/index' {
  declare module.exports: $Exports<'@reach/router/website/src'>;
}
declare module '@reach/router/website/src/index.js' {
  declare module.exports: $Exports<'@reach/router/website/src'>;
}
declare module '@reach/router/website/src/Logo.js' {
  declare module.exports: $Exports<'@reach/router/website/src/Logo'>;
}
declare module '@reach/router/website/src/Nav.js' {
  declare module.exports: $Exports<'@reach/router/website/src/Nav'>;
}
declare module '@reach/router/website/src/polyfills.js' {
  declare module.exports: $Exports<'@reach/router/website/src/polyfills'>;
}
declare module '@reach/router/website/src/theme.js' {
  declare module.exports: $Exports<'@reach/router/website/src/theme'>;
}
declare module '@reach/router/website/webpack.config.js' {
  declare module.exports: $Exports<'@reach/router/website/webpack.config'>;
}
