// flow-typed signature: 68edf770399804368faab5f6d1bb3cae
// flow-typed version: <<STUB>>/@babel/plugin-syntax-top-level-await_v7.14.5/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-syntax-top-level-await'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-syntax-top-level-await' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-syntax-top-level-await/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-syntax-top-level-await/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-syntax-top-level-await/lib'>;
}
declare module '@babel/plugin-syntax-top-level-await/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-syntax-top-level-await/lib'>;
}
