import * as pack from './webpack.setup.mjs';
import HtmlWebpackPlugin from 'html-webpack-plugin';
import webpack from 'webpack';
import webpackBaseConfig from './webpack.base.config.mjs';


export default webpackBaseConfig({
  entryUnshift: [
    'react-devtools',
    'webpack-hot-middleware-2/client'
  ],
  plugins: [

    new webpack.HotModuleReplacementPlugin(),

    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: pack.env.config.HTML_INDEX,
    }),

    // new ScriptExtHtmlWebpackPlugin({
    //   module: /(workers|sw)/,
    // }),
  ],
})
