// flow-typed signature: b583ba64039c276c345b5885c5f13157
// flow-typed version: <<STUB>>/cls-rtracer_v2.6.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cls-rtracer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cls-rtracer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cls-rtracer/src/rtracer' {
  declare module.exports: any;
}

declare module 'cls-rtracer/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cls-rtracer/index' {
  declare module.exports: $Exports<'cls-rtracer'>;
}
declare module 'cls-rtracer/index.js' {
  declare module.exports: $Exports<'cls-rtracer'>;
}
declare module 'cls-rtracer/src/rtracer.js' {
  declare module.exports: $Exports<'cls-rtracer/src/rtracer'>;
}
declare module 'cls-rtracer/src/util.js' {
  declare module.exports: $Exports<'cls-rtracer/src/util'>;
}
