// flow-typed signature: 0771588e40e6a8b0e665a4677596f05b
// flow-typed version: <<STUB>>/es-main_v1.0.2/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es-main'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es-main' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es-main/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es-main/main.js' {
  declare module.exports: $Exports<'es-main/main'>;
}
