// flow-typed signature: e2b75c97bb0a072910470ac5cf2b2e92
// flow-typed version: <<STUB>>/koa-charset_v2.0.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-charset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-charset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-charset/example' {
  declare module.exports: any;
}

declare module 'koa-charset/test/charset.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-charset/example.js' {
  declare module.exports: $Exports<'koa-charset/example'>;
}
declare module 'koa-charset/index' {
  declare module.exports: $Exports<'koa-charset'>;
}
declare module 'koa-charset/index.js' {
  declare module.exports: $Exports<'koa-charset'>;
}
declare module 'koa-charset/test/charset.test.js' {
  declare module.exports: $Exports<'koa-charset/test/charset.test'>;
}
