// flow-typed signature: 9bf51f87aa170206c0f3510690abf93f
// flow-typed version: <<STUB>>/koa-qs_v3.0.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-qs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-qs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-qs/index' {
  declare module.exports: $Exports<'koa-qs'>;
}
declare module 'koa-qs/index.js' {
  declare module.exports: $Exports<'koa-qs'>;
}
