// flow-typed signature: 3937cae962333088bcf63356e30153b7
// flow-typed version: <<STUB>>/koa-ratelimit_v5.0.1/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-ratelimit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-ratelimit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-ratelimit/limiter/memory' {
  declare module.exports: any;
}

declare module 'koa-ratelimit/limiter/redis' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-ratelimit/index' {
  declare module.exports: $Exports<'koa-ratelimit'>;
}
declare module 'koa-ratelimit/index.js' {
  declare module.exports: $Exports<'koa-ratelimit'>;
}
declare module 'koa-ratelimit/limiter/memory.js' {
  declare module.exports: $Exports<'koa-ratelimit/limiter/memory'>;
}
declare module 'koa-ratelimit/limiter/redis.js' {
  declare module.exports: $Exports<'koa-ratelimit/limiter/redis'>;
}
