// flow-typed signature: b19e8851119755a51199f24bf0c74831
// flow-typed version: <<STUB>>/@folder/xdg_v3.1.2/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@folder/xdg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@folder/xdg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@folder/xdg/lib/expand' {
  declare module.exports: any;
}

declare module '@folder/xdg/lib/userdirs' {
  declare module.exports: any;
}

declare module '@folder/xdg/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@folder/xdg/index' {
  declare module.exports: $Exports<'@folder/xdg'>;
}
declare module '@folder/xdg/index.js' {
  declare module.exports: $Exports<'@folder/xdg'>;
}
declare module '@folder/xdg/lib/expand.js' {
  declare module.exports: $Exports<'@folder/xdg/lib/expand'>;
}
declare module '@folder/xdg/lib/userdirs.js' {
  declare module.exports: $Exports<'@folder/xdg/lib/userdirs'>;
}
declare module '@folder/xdg/lib/utils.js' {
  declare module.exports: $Exports<'@folder/xdg/lib/utils'>;
}
