// flow-typed signature: fe081f454176adac9302beb0668b7e98
// flow-typed version: <<STUB>>/@messageformat/react_v1.0.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@messageformat/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@messageformat/react' {
  declare module.exports: any;
}
