// flow-typed signature: 9d99205e2eb5cadec99aef24e80e8078
// flow-typed version: <<STUB>>/@nodeproto/jsync_vworkspace:0.0.0/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nodeproto/jsync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nodeproto/jsync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nodeproto/jsync/bin/jsync' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/dist/constants' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/dist/getFiles' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/dist' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/dist/libdefs' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/dist/syncFiles' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@babel/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@babel/eslint-parser_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@babel/eslint-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@babel/runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@changesets/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/configproto_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/eslint-config_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/prettier-config_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/shared_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/testproto_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@octokit/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@octokit/rest_v18.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@swc/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@swc/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/babel-preset-nodeproto_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/browserslist_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/chokidar_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/chokidar-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/colors_v1.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/env-cmd_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/eslint-config-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-fb-flow_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-html_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-json_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-markdown_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-node_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-promise_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-yml_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/flow-remove-types_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/fs-extra_v10.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/glob_v7.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/jest_v27.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/md5_v2.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/regenerator-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/rimraf_v3.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/ultra-runner_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/uvu_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/yaml-eslint-parser_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/src/libdefs' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nodeproto/jsync/bin/jsync.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/bin/jsync'>;
}
declare module '@nodeproto/jsync/dist/constants.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/dist/constants'>;
}
declare module '@nodeproto/jsync/dist/getFiles.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/dist/getFiles'>;
}
declare module '@nodeproto/jsync/dist/index' {
  declare module.exports: $Exports<'@nodeproto/jsync/dist'>;
}
declare module '@nodeproto/jsync/dist/index.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/dist'>;
}
declare module '@nodeproto/jsync/dist/libdefs/index' {
  declare module.exports: $Exports<'@nodeproto/jsync/dist/libdefs'>;
}
declare module '@nodeproto/jsync/dist/libdefs/index.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/dist/libdefs'>;
}
declare module '@nodeproto/jsync/dist/syncFiles.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/dist/syncFiles'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@babel/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@babel/cli_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@babel/eslint-parser_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@babel/eslint-parser_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@babel/eslint-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@babel/eslint-plugin_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@babel/runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@babel/runtime_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@changesets/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@changesets/cli_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/configproto_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@nodeproto/configproto_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/eslint-config_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@nodeproto/eslint-config_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/prettier-config_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@nodeproto/prettier-config_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/shared_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@nodeproto/shared_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/testproto_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@nodeproto/testproto_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@octokit/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@octokit/core_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@octokit/rest_v18.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@octokit/rest_v18.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@swc/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@swc/cli_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@swc/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@swc/core_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/babel-preset-nodeproto_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/babel-preset-nodeproto_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/browserslist_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/browserslist_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/chokidar_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/chokidar_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/chokidar-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/chokidar-cli_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/colors_v1.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/colors_v1.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/env-cmd_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/env-cmd_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/eslint-config-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/eslint-config-prettier_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-fb-flow_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/eslint-plugin-fb-flow_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-html_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/eslint-plugin-html_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-json_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/eslint-plugin-json_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-markdown_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/eslint-plugin-markdown_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-node_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/eslint-plugin-node_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/eslint-plugin-prettier_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-promise_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/eslint-plugin-promise_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/eslint-plugin-yml_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/eslint-plugin-yml_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/flow-remove-types_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/flow-remove-types_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/fs-extra_v10.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/fs-extra_v10.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/glob_v7.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/glob_v7.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/husky_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/jest_v27.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/jest_v27.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/md5_v2.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/md5_v2.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/prettier_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/regenerator-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/regenerator-runtime_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/rimraf_v3.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/rimraf_v3.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/ultra-runner_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/ultra-runner_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/uvu_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/uvu_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/yaml-eslint-parser_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/yaml-eslint-parser_vx.x.x'>;
}
declare module '@nodeproto/jsync/src/libdefs/index' {
  declare module.exports: $Exports<'@nodeproto/jsync/src/libdefs'>;
}
declare module '@nodeproto/jsync/src/libdefs/index.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/src/libdefs'>;
}
