// flow-typed signature: 0d8318fff899bfbb63abe92207edccd0
// flow-typed version: <<STUB>>/@nodeproto/prettier-config_vworkspace:0.0.0/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nodeproto/prettier-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nodeproto/prettier-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@nodeproto/prettier-config/index' {
  declare module.exports: $Exports<'@nodeproto/prettier-config'>;
}
declare module '@nodeproto/prettier-config/index.js' {
  declare module.exports: $Exports<'@nodeproto/prettier-config'>;
}
