// flow-typed signature: 2ec1e80eec801a1c50893d53eef2dac6
// flow-typed version: <<STUB>>/@babel/eslint-parser_v7.16.3/flow_v0.164.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
