// flow-typed signature: ca7523cb5bd7f977b2c8f5e169fe1798
// flow-typed version: <<STUB>>/@babel/plugin-syntax-jsx_v7.14.5/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-syntax-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-syntax-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-syntax-jsx/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-syntax-jsx/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-syntax-jsx/lib'>;
}
declare module '@babel/plugin-syntax-jsx/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-syntax-jsx/lib'>;
}
