// flow-typed signature: caf696a681f42c9640f1ad5f549ec9a5
// flow-typed version: <<STUB>>/@nodeproto/wtf_vworkspace:0.0.0/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nodeproto/wtf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nodeproto/wtf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nodeproto/wtf/dist/dirs' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/dist/esmain' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/dist/fsproto' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/dist' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/dist/libdefs' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@babel/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@babel/eslint-parser_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@babel/eslint-plugin_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@babel/runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@changesets/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@folder/readdir_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@folder/xdg_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@nodeproto/configproto_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@nodeproto/jsync_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@nodeproto/shared_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@nodeproto/testproto_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@octokit/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@swc/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/@swc/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/browserslist_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/chokidar-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/contains-path_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/dirent_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/env-cmd_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/eslint-config-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-fb-flow_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-html_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-json_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-markdown_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-node_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-promise_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-yml_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/flow-remove-types_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/fs-extra_v10.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/global-dirs_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/jsonc-simple-parser_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/memfs_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/mkdirp_v1.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/regenerator-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/symlink-dir_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/ultra-runner_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/uvu_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/flow-typed/npm/yaml-eslint-parser_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/wtf/src/libdefs' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nodeproto/wtf/dist/dirs.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/dist/dirs'>;
}
declare module '@nodeproto/wtf/dist/esmain.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/dist/esmain'>;
}
declare module '@nodeproto/wtf/dist/fsproto.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/dist/fsproto'>;
}
declare module '@nodeproto/wtf/dist/index' {
  declare module.exports: $Exports<'@nodeproto/wtf/dist'>;
}
declare module '@nodeproto/wtf/dist/index.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/dist'>;
}
declare module '@nodeproto/wtf/dist/libdefs/index' {
  declare module.exports: $Exports<'@nodeproto/wtf/dist/libdefs'>;
}
declare module '@nodeproto/wtf/dist/libdefs/index.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/dist/libdefs'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@babel/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@babel/cli_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@babel/eslint-parser_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@babel/eslint-parser_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@babel/eslint-plugin_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@babel/eslint-plugin_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@babel/runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@babel/runtime_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@changesets/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@changesets/cli_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@folder/readdir_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@folder/readdir_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@folder/xdg_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@folder/xdg_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@nodeproto/configproto_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@nodeproto/configproto_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@nodeproto/jsync_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@nodeproto/jsync_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@nodeproto/shared_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@nodeproto/shared_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@nodeproto/testproto_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@nodeproto/testproto_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@octokit/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@octokit/core_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@swc/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@swc/cli_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/@swc/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/@swc/core_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/browserslist_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/browserslist_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/chokidar-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/chokidar-cli_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/contains-path_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/contains-path_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/dirent_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/dirent_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/env-cmd_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/env-cmd_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/eslint-config-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/eslint-config-prettier_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-fb-flow_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/eslint-plugin-fb-flow_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-html_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/eslint-plugin-html_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-json_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/eslint-plugin-json_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-markdown_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/eslint-plugin-markdown_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-node_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/eslint-plugin-node_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/eslint-plugin-prettier_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-promise_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/eslint-plugin-promise_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/eslint-plugin-yml_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/eslint-plugin-yml_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/flow-remove-types_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/flow-remove-types_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/fs-extra_v10.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/fs-extra_v10.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/global-dirs_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/global-dirs_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/jsonc-simple-parser_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/jsonc-simple-parser_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/memfs_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/memfs_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/mkdirp_v1.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/mkdirp_v1.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/prettier_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/regenerator-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/regenerator-runtime_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/symlink-dir_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/symlink-dir_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/ultra-runner_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/ultra-runner_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/uvu_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/uvu_vx.x.x'>;
}
declare module '@nodeproto/wtf/flow-typed/npm/yaml-eslint-parser_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/flow-typed/npm/yaml-eslint-parser_vx.x.x'>;
}
declare module '@nodeproto/wtf/src/libdefs/index' {
  declare module.exports: $Exports<'@nodeproto/wtf/src/libdefs'>;
}
declare module '@nodeproto/wtf/src/libdefs/index.js' {
  declare module.exports: $Exports<'@nodeproto/wtf/src/libdefs'>;
}
