// flow-typed signature: 472e88838eaa62ed71d8625cc52f268d
// flow-typed version: <<STUB>>/@nodeproto/jsync_vworkspace:*/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nodeproto/jsync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nodeproto/jsync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nodeproto/jsync/bin/jsync' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@babel/eslint-parser_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@babel/runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@changesets/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/configproto_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/shared_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/testproto_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@octokit/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@swc/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/@swc/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/chokidar_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/chokidar-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/env-cmd_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/flow-remove-types_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/fs-extra_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/regenerator-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/ultra-runner_vx.x.x' {
  declare module.exports: any;
}

declare module '@nodeproto/jsync/flow-typed/npm/uvu_vx.x.x' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nodeproto/jsync/bin/jsync.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/bin/jsync'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@babel/eslint-parser_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@babel/eslint-parser_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@babel/runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@babel/runtime_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@changesets/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@changesets/cli_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/configproto_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@nodeproto/configproto_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/shared_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@nodeproto/shared_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@nodeproto/testproto_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@nodeproto/testproto_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@octokit/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@octokit/core_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@swc/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@swc/cli_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/@swc/core_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/@swc/core_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/chokidar_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/chokidar_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/chokidar-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/chokidar-cli_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/env-cmd_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/env-cmd_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/flow-remove-types_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/flow-remove-types_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/fs-extra_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/fs-extra_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/regenerator-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/regenerator-runtime_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/ultra-runner_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/ultra-runner_vx.x.x'>;
}
declare module '@nodeproto/jsync/flow-typed/npm/uvu_vx.x.x.js' {
  declare module.exports: $Exports<'@nodeproto/jsync/flow-typed/npm/uvu_vx.x.x'>;
}
