// flow-typed signature: d51fd1957e3b3bb8ee5421c603486739
// flow-typed version: <<STUB>>/csv-loader_v3.0.3/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csv-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csv-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'csv-loader/index' {
  declare module.exports: $Exports<'csv-loader'>;
}
declare module 'csv-loader/index.js' {
  declare module.exports: $Exports<'csv-loader'>;
}
