// flow-typed signature: 0ac495ed2fb9bbbfe44bd4db3f5b4f71
// flow-typed version: <<STUB>>/esbuild-plugin-manifest_v0.5.0/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esbuild-plugin-manifest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esbuild-plugin-manifest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esbuild-plugin-manifest/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esbuild-plugin-manifest/lib/index' {
  declare module.exports: $Exports<'esbuild-plugin-manifest/lib'>;
}
declare module 'esbuild-plugin-manifest/lib/index.js' {
  declare module.exports: $Exports<'esbuild-plugin-manifest/lib'>;
}
