// flow-typed signature: 4f826aec36e624d4cbda5199f7a35a01
// flow-typed version: <<STUB>>/http-terminator_v3.0.0/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-terminator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-terminator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'http-terminator/dist/src/factories/createHttpTerminator' {
  declare module.exports: any;
}

declare module 'http-terminator/dist/src/factories/createInternalHttpTerminator' {
  declare module.exports: any;
}

declare module 'http-terminator/dist/src' {
  declare module.exports: any;
}

declare module 'http-terminator/dist/src/Logger' {
  declare module.exports: any;
}

declare module 'http-terminator/dist/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'http-terminator/dist/src/factories/createHttpTerminator.js' {
  declare module.exports: $Exports<'http-terminator/dist/src/factories/createHttpTerminator'>;
}
declare module 'http-terminator/dist/src/factories/createInternalHttpTerminator.js' {
  declare module.exports: $Exports<'http-terminator/dist/src/factories/createInternalHttpTerminator'>;
}
declare module 'http-terminator/dist/src/index' {
  declare module.exports: $Exports<'http-terminator/dist/src'>;
}
declare module 'http-terminator/dist/src/index.js' {
  declare module.exports: $Exports<'http-terminator/dist/src'>;
}
declare module 'http-terminator/dist/src/Logger.js' {
  declare module.exports: $Exports<'http-terminator/dist/src/Logger'>;
}
declare module 'http-terminator/dist/src/types.js' {
  declare module.exports: $Exports<'http-terminator/dist/src/types'>;
}
