// flow-typed signature: 230225013f82810fd5b3e20bb3771b75
// flow-typed version: <<STUB>>/mini-svg-data-uri_v1.3.3/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mini-svg-data-uri'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mini-svg-data-uri' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mini-svg-data-uri/cli' {
  declare module.exports: any;
}

declare module 'mini-svg-data-uri/shorter-css-color-names' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mini-svg-data-uri/cli.js' {
  declare module.exports: $Exports<'mini-svg-data-uri/cli'>;
}
declare module 'mini-svg-data-uri/index' {
  declare module.exports: $Exports<'mini-svg-data-uri'>;
}
declare module 'mini-svg-data-uri/index.js' {
  declare module.exports: $Exports<'mini-svg-data-uri'>;
}
declare module 'mini-svg-data-uri/shorter-css-color-names.js' {
  declare module.exports: $Exports<'mini-svg-data-uri/shorter-css-color-names'>;
}
