// flow-typed signature: 816c6c751e1457a8abcd036f48a2d429
// flow-typed version: <<STUB>>/ultra-runner_v3.10.5/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ultra-runner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ultra-runner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ultra-runner/bin/ultra' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/build' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/cli' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/concurrency' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/formatter' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/git' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/monitor' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/options' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/package' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/parser' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/pnp' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/process' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/runner' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/spawn' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/spinner' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/symbols' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/terminal' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/workspace' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/workspace.providers' {
  declare module.exports: any;
}

declare module 'ultra-runner/lib/yargs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ultra-runner/bin/ultra.js' {
  declare module.exports: $Exports<'ultra-runner/bin/ultra'>;
}
declare module 'ultra-runner/lib/build.js' {
  declare module.exports: $Exports<'ultra-runner/lib/build'>;
}
declare module 'ultra-runner/lib/cli.js' {
  declare module.exports: $Exports<'ultra-runner/lib/cli'>;
}
declare module 'ultra-runner/lib/concurrency.js' {
  declare module.exports: $Exports<'ultra-runner/lib/concurrency'>;
}
declare module 'ultra-runner/lib/formatter.js' {
  declare module.exports: $Exports<'ultra-runner/lib/formatter'>;
}
declare module 'ultra-runner/lib/git.js' {
  declare module.exports: $Exports<'ultra-runner/lib/git'>;
}
declare module 'ultra-runner/lib/index' {
  declare module.exports: $Exports<'ultra-runner/lib'>;
}
declare module 'ultra-runner/lib/index.js' {
  declare module.exports: $Exports<'ultra-runner/lib'>;
}
declare module 'ultra-runner/lib/monitor.js' {
  declare module.exports: $Exports<'ultra-runner/lib/monitor'>;
}
declare module 'ultra-runner/lib/options.js' {
  declare module.exports: $Exports<'ultra-runner/lib/options'>;
}
declare module 'ultra-runner/lib/package.js' {
  declare module.exports: $Exports<'ultra-runner/lib/package'>;
}
declare module 'ultra-runner/lib/parser.js' {
  declare module.exports: $Exports<'ultra-runner/lib/parser'>;
}
declare module 'ultra-runner/lib/pnp.js' {
  declare module.exports: $Exports<'ultra-runner/lib/pnp'>;
}
declare module 'ultra-runner/lib/process.js' {
  declare module.exports: $Exports<'ultra-runner/lib/process'>;
}
declare module 'ultra-runner/lib/runner.js' {
  declare module.exports: $Exports<'ultra-runner/lib/runner'>;
}
declare module 'ultra-runner/lib/spawn.js' {
  declare module.exports: $Exports<'ultra-runner/lib/spawn'>;
}
declare module 'ultra-runner/lib/spinner.js' {
  declare module.exports: $Exports<'ultra-runner/lib/spinner'>;
}
declare module 'ultra-runner/lib/symbols.js' {
  declare module.exports: $Exports<'ultra-runner/lib/symbols'>;
}
declare module 'ultra-runner/lib/terminal.js' {
  declare module.exports: $Exports<'ultra-runner/lib/terminal'>;
}
declare module 'ultra-runner/lib/workspace.js' {
  declare module.exports: $Exports<'ultra-runner/lib/workspace'>;
}
declare module 'ultra-runner/lib/workspace.providers.js' {
  declare module.exports: $Exports<'ultra-runner/lib/workspace.providers'>;
}
declare module 'ultra-runner/lib/yargs.js' {
  declare module.exports: $Exports<'ultra-runner/lib/yargs'>;
}
