// flow-typed signature: c6bfef0b02747d0246f4f514b6d01f0d
// flow-typed version: <<STUB>>/webpack-manifest-plugin_v5.0.0/flow_v0.176.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-manifest-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-manifest-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-manifest-plugin/dist/helpers' {
  declare module.exports: any;
}

declare module 'webpack-manifest-plugin/dist/hooks' {
  declare module.exports: any;
}

declare module 'webpack-manifest-plugin/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-manifest-plugin/dist/helpers.js' {
  declare module.exports: $Exports<'webpack-manifest-plugin/dist/helpers'>;
}
declare module 'webpack-manifest-plugin/dist/hooks.js' {
  declare module.exports: $Exports<'webpack-manifest-plugin/dist/hooks'>;
}
declare module 'webpack-manifest-plugin/dist/index' {
  declare module.exports: $Exports<'webpack-manifest-plugin/dist'>;
}
declare module 'webpack-manifest-plugin/dist/index.js' {
  declare module.exports: $Exports<'webpack-manifest-plugin/dist'>;
}
