// flow-typed signature: e74a885b1e255bd00782052a9301a78d
// flow-typed version: <<STUB>>/webpack-hot-middleware-2_v2.25.2/flow_v0.161.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-hot-middleware-2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-hot-middleware-2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-hot-middleware-2/bffs' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware-2/bffs/useKoa2' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware-2/client-overlay' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware-2/client' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware-2/helpers' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware-2/middleware' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware-2/process-update' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-hot-middleware-2/bffs/index' {
  declare module.exports: $Exports<'webpack-hot-middleware-2/bffs'>;
}
declare module 'webpack-hot-middleware-2/bffs/index.js' {
  declare module.exports: $Exports<'webpack-hot-middleware-2/bffs'>;
}
declare module 'webpack-hot-middleware-2/bffs/useKoa2.js' {
  declare module.exports: $Exports<'webpack-hot-middleware-2/bffs/useKoa2'>;
}
declare module 'webpack-hot-middleware-2/client-overlay.js' {
  declare module.exports: $Exports<'webpack-hot-middleware-2/client-overlay'>;
}
declare module 'webpack-hot-middleware-2/client.js' {
  declare module.exports: $Exports<'webpack-hot-middleware-2/client'>;
}
declare module 'webpack-hot-middleware-2/helpers.js' {
  declare module.exports: $Exports<'webpack-hot-middleware-2/helpers'>;
}
declare module 'webpack-hot-middleware-2/middleware.js' {
  declare module.exports: $Exports<'webpack-hot-middleware-2/middleware'>;
}
declare module 'webpack-hot-middleware-2/process-update.js' {
  declare module.exports: $Exports<'webpack-hot-middleware-2/process-update'>;
}
