// flow-typed signature: a77ae191d43110b50a362e83dbd41cbc
// flow-typed version: <<STUB>>/@octokit/core_v3.5.1/flow_v0.170.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@octokit/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@octokit/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@octokit/core/dist-node' {
  declare module.exports: any;
}

declare module '@octokit/core/dist-src' {
  declare module.exports: any;
}

declare module '@octokit/core/dist-src/types' {
  declare module.exports: any;
}

declare module '@octokit/core/dist-src/version' {
  declare module.exports: any;
}

declare module '@octokit/core/dist-web' {
  declare module.exports: any;
}

// Filename aliases
declare module '@octokit/core/dist-node/index' {
  declare module.exports: $Exports<'@octokit/core/dist-node'>;
}
declare module '@octokit/core/dist-node/index.js' {
  declare module.exports: $Exports<'@octokit/core/dist-node'>;
}
declare module '@octokit/core/dist-src/index' {
  declare module.exports: $Exports<'@octokit/core/dist-src'>;
}
declare module '@octokit/core/dist-src/index.js' {
  declare module.exports: $Exports<'@octokit/core/dist-src'>;
}
declare module '@octokit/core/dist-src/types.js' {
  declare module.exports: $Exports<'@octokit/core/dist-src/types'>;
}
declare module '@octokit/core/dist-src/version.js' {
  declare module.exports: $Exports<'@octokit/core/dist-src/version'>;
}
declare module '@octokit/core/dist-web/index' {
  declare module.exports: $Exports<'@octokit/core/dist-web'>;
}
declare module '@octokit/core/dist-web/index.js' {
  declare module.exports: $Exports<'@octokit/core/dist-web'>;
}
